<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 t-tests | MSc Conversion in Psychological Studies</title>
  <meta name="description" content="This book contains the materials for the MSc Conversion in Psychological Studies/Science." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 t-tests | MSc Conversion in Psychological Studies" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This book contains the materials for the MSc Conversion in Psychological Studies/Science." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 t-tests | MSc Conversion in Psychological Studies" />
  
  <meta name="twitter:description" content="This book contains the materials for the MSc Conversion in Psychological Studies/Science." />
  



<meta name="date" content="2021-05-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="correlation.html"/>
<link rel="next" href="power-and-error.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="include/psyteachr.css" type="text/css" />
<link rel="stylesheet" href="include/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">MSc Conversion in Psychological Studies/Science (face-to-face)</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#how-to-use-this-book-and-the-walkthrough-videos"><i class="fa fa-check"></i><b>0.1</b> How to use this book and the walkthrough videos</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#intended-learning-outcomes"><i class="fa fa-check"></i><b>0.2</b> Intended Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="programming-basics.html"><a href="programming-basics.html"><i class="fa fa-check"></i><b>1</b> Programming basics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="programming-basics.html"><a href="programming-basics.html#r-and-rstudio"><i class="fa fa-check"></i><b>1.1</b> R and RStudio</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="programming-basics.html"><a href="programming-basics.html#r-server"><i class="fa fa-check"></i><b>1.1.1</b> R server</a></li>
<li class="chapter" data-level="1.1.2" data-path="programming-basics.html"><a href="programming-basics.html#installing-r-on-your-computer"><i class="fa fa-check"></i><b>1.1.2</b> Installing R on your computer</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="programming-basics.html"><a href="programming-basics.html#getting-to-know-r-studio"><i class="fa fa-check"></i><b>1.2</b> Getting to know R Studio</a></li>
<li class="chapter" data-level="1.3" data-path="programming-basics.html"><a href="programming-basics.html#console-vs.-scripts"><i class="fa fa-check"></i><b>1.3</b> Console vs. scripts</a></li>
<li class="chapter" data-level="1.4" data-path="programming-basics.html"><a href="programming-basics.html#functions-and-arguments"><i class="fa fa-check"></i><b>1.4</b> Functions and arguments</a></li>
<li class="chapter" data-level="1.5" data-path="programming-basics.html"><a href="programming-basics.html#activity-1"><i class="fa fa-check"></i><b>1.5</b> Activity 1</a></li>
<li class="chapter" data-level="1.6" data-path="programming-basics.html"><a href="programming-basics.html#activity-2"><i class="fa fa-check"></i><b>1.6</b> Activity 2</a></li>
<li class="chapter" data-level="1.7" data-path="programming-basics.html"><a href="programming-basics.html#argument-names"><i class="fa fa-check"></i><b>1.7</b> Argument names</a></li>
<li class="chapter" data-level="1.8" data-path="programming-basics.html"><a href="programming-basics.html#tab-auto-complete"><i class="fa fa-check"></i><b>1.8</b> Tab auto-complete</a></li>
<li class="chapter" data-level="1.9" data-path="programming-basics.html"><a href="programming-basics.html#packages"><i class="fa fa-check"></i><b>1.9</b> Base R and packages</a></li>
<li class="chapter" data-level="1.10" data-path="programming-basics.html"><a href="programming-basics.html#activity-3-install-the-tidyverse-optional"><i class="fa fa-check"></i><b>1.10</b> Activity 3: Install the tidyverse (optional)</a></li>
<li class="chapter" data-level="1.11" data-path="programming-basics.html"><a href="programming-basics.html#activity-4-load-the-tidyverse"><i class="fa fa-check"></i><b>1.11</b> Activity 4: Load the tidyverse</a></li>
<li class="chapter" data-level="1.12" data-path="programming-basics.html"><a href="programming-basics.html#package-updates"><i class="fa fa-check"></i><b>1.12</b> Package updates</a></li>
<li class="chapter" data-level="1.13" data-path="programming-basics.html"><a href="programming-basics.html#conflicts"><i class="fa fa-check"></i><b>1.13</b> Package conflicts</a></li>
<li class="chapter" data-level="1.14" data-path="programming-basics.html"><a href="programming-basics.html#objects"><i class="fa fa-check"></i><b>1.14</b> Objects</a></li>
<li class="chapter" data-level="1.15" data-path="programming-basics.html"><a href="programming-basics.html#activity-5-create-some-objects"><i class="fa fa-check"></i><b>1.15</b> Activity 5: Create some objects</a></li>
<li class="chapter" data-level="1.16" data-path="programming-basics.html"><a href="programming-basics.html#looking-after-the-environment"><i class="fa fa-check"></i><b>1.16</b> Looking after the environment</a></li>
<li class="chapter" data-level="1.17" data-path="programming-basics.html"><a href="programming-basics.html#global-options"><i class="fa fa-check"></i><b>1.17</b> Global options</a></li>
<li class="chapter" data-level="1.18" data-path="programming-basics.html"><a href="programming-basics.html#r-sessions"><i class="fa fa-check"></i><b>1.18</b> R sessions</a></li>
<li class="chapter" data-level="1.19" data-path="programming-basics.html"><a href="programming-basics.html#activity-6"><i class="fa fa-check"></i><b>1.19</b> Activity 6</a></li>
<li class="chapter" data-level="1.20" data-path="programming-basics.html"><a href="programming-basics.html#how-to-cite-r-and-rstudio"><i class="fa fa-check"></i><b>1.20</b> How to cite R and RStudio</a></li>
<li class="chapter" data-level="1.21" data-path="programming-basics.html"><a href="programming-basics.html#help-and-additional-resources"><i class="fa fa-check"></i><b>1.21</b> Help and additional resources</a></li>
<li class="chapter" data-level="1.22" data-path="programming-basics.html"><a href="programming-basics.html#debugging-tips"><i class="fa fa-check"></i><b>1.22</b> Debugging tips</a></li>
<li class="chapter" data-level="1.23" data-path="programming-basics.html"><a href="programming-basics.html#test-yourself"><i class="fa fa-check"></i><b>1.23</b> Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro-to-r.html"><a href="intro-to-r.html"><i class="fa fa-check"></i><b>2</b> Intro to R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="intro-to-r.html"><a href="intro-to-r.html#intro-a1"><i class="fa fa-check"></i><b>2.1</b> Activity 1: Create the working directory</a></li>
<li class="chapter" data-level="2.2" data-path="intro-to-r.html"><a href="intro-to-r.html#intro-a1b"><i class="fa fa-check"></i><b>2.2</b> Activity 1b: Upload data files to the server</a></li>
<li class="chapter" data-level="2.3" data-path="intro-to-r.html"><a href="intro-to-r.html#intro-a2"><i class="fa fa-check"></i><b>2.3</b> Activity 2: Set the working directory</a></li>
<li class="chapter" data-level="2.4" data-path="intro-to-r.html"><a href="intro-to-r.html#r-markdown-for-r-book-work-and-portfolio-assignments"><i class="fa fa-check"></i><b>2.4</b> R Markdown for R book work and portfolio assignments</a></li>
<li class="chapter" data-level="2.5" data-path="intro-to-r.html"><a href="intro-to-r.html#intro-a3"><i class="fa fa-check"></i><b>2.5</b> Activity 3: Open and save a new R Markdown document</a></li>
<li class="chapter" data-level="2.6" data-path="intro-to-r.html"><a href="intro-to-r.html#intro-a4"><i class="fa fa-check"></i><b>2.6</b> Activity 4: Create a new code chunk</a></li>
<li class="chapter" data-level="2.7" data-path="intro-to-r.html"><a href="intro-to-r.html#intro-a5"><i class="fa fa-check"></i><b>2.7</b> Activity 5: Write some code</a></li>
<li class="chapter" data-level="2.8" data-path="intro-to-r.html"><a href="intro-to-r.html#running-code"><i class="fa fa-check"></i><b>2.8</b> Running code</a></li>
<li class="chapter" data-level="2.9" data-path="intro-to-r.html"><a href="intro-to-r.html#intro-a6"><i class="fa fa-check"></i><b>2.9</b> Activity 6: Run your code</a></li>
<li class="chapter" data-level="2.10" data-path="intro-to-r.html"><a href="intro-to-r.html#intro-a7"><i class="fa fa-check"></i><b>2.10</b> Activity 7: Inline code</a></li>
<li class="chapter" data-level="2.11" data-path="intro-to-r.html"><a href="intro-to-r.html#intro-a8"><i class="fa fa-check"></i><b>2.11</b> Activity 8: Knitting your file</a></li>
<li class="chapter" data-level="2.12" data-path="intro-to-r.html"><a href="intro-to-r.html#intro-a9"><i class="fa fa-check"></i><b>2.12</b> Activity 9: Make R your own</a></li>
<li class="chapter" data-level="2.13" data-path="intro-to-r.html"><a href="intro-to-r.html#finished"><i class="fa fa-check"></i><b>2.13</b> Finished</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="loading-data.html"><a href="loading-data.html"><i class="fa fa-check"></i><b>3</b> Loading data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="loading-data.html"><a href="loading-data.html#getting-data-ready-to-work-with"><i class="fa fa-check"></i><b>3.1</b> Getting data ready to work with</a></li>
<li class="chapter" data-level="3.2" data-path="loading-data.html"><a href="loading-data.html#ld-a1"><i class="fa fa-check"></i><b>3.2</b> Activity 1: Set-up Loading Data</a></li>
<li class="chapter" data-level="3.3" data-path="loading-data.html"><a href="loading-data.html#ld-a2"><i class="fa fa-check"></i><b>3.3</b> Activity 2: Load in the package</a></li>
<li class="chapter" data-level="3.4" data-path="loading-data.html"><a href="loading-data.html#open-data"><i class="fa fa-check"></i><b>3.4</b> Open data</a></li>
<li class="chapter" data-level="3.5" data-path="loading-data.html"><a href="loading-data.html#ld-a3"><i class="fa fa-check"></i><b>3.5</b> Activity 3: Read in data</a></li>
<li class="chapter" data-level="3.6" data-path="loading-data.html"><a href="loading-data.html#ld-a4"><i class="fa fa-check"></i><b>3.6</b> Activity 4: Check yo’ data</a></li>
<li class="chapter" data-level="3.7" data-path="loading-data.html"><a href="loading-data.html#ld-a5"><i class="fa fa-check"></i><b>3.7</b> Activity 5: Join the files together</a></li>
<li class="chapter" data-level="3.8" data-path="loading-data.html"><a href="loading-data.html#ld-a6"><i class="fa fa-check"></i><b>3.8</b> Activity 6: Pull out variables of interest</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="loading-data.html"><a href="loading-data.html#ld-fin"><i class="fa fa-check"></i><b>3.8.1</b> Finished!</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="loading-data.html"><a href="loading-data.html#ld-debug"><i class="fa fa-check"></i><b>3.9</b> Debugging tips</a></li>
<li class="chapter" data-level="3.10" data-path="loading-data.html"><a href="loading-data.html#ld-debugex"><i class="fa fa-check"></i><b>3.10</b> Debugging exercises</a></li>
<li class="chapter" data-level="3.11" data-path="loading-data.html"><a href="loading-data.html#ld-test"><i class="fa fa-check"></i><b>3.11</b> Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html"><i class="fa fa-check"></i><b>4</b> Data wrangling 1</a>
<ul>
<li class="chapter" data-level="4.1" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#tidyverse"><i class="fa fa-check"></i><b>4.1</b> Tidyverse</a></li>
<li class="chapter" data-level="4.2" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#the-babynames-database"><i class="fa fa-check"></i><b>4.2</b> The <code>babynames</code> database</a></li>
<li class="chapter" data-level="4.3" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#dw1-a1"><i class="fa fa-check"></i><b>4.3</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="4.4" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#dw1-a2"><i class="fa fa-check"></i><b>4.4</b> Activity 2: Look at the data</a></li>
<li class="chapter" data-level="4.5" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#dw1-a3"><i class="fa fa-check"></i><b>4.5</b> Activity 3: Your first plot</a></li>
<li class="chapter" data-level="4.6" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#dw1-a4"><i class="fa fa-check"></i><b>4.6</b> Activity 4: Selecting variables of interest</a></li>
<li class="chapter" data-level="4.7" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#dw1-a5"><i class="fa fa-check"></i><b>4.7</b> Activity 5: Arranging the data</a></li>
<li class="chapter" data-level="4.8" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#dw1-a6"><i class="fa fa-check"></i><b>4.8</b> Activity 6: Using filter to select observations</a></li>
<li class="chapter" data-level="4.9" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#dw1-a7"><i class="fa fa-check"></i><b>4.9</b> Activity 7: Creating new variables</a></li>
<li class="chapter" data-level="4.10" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#dw1-a8"><i class="fa fa-check"></i><b>4.10</b> Activity 8: Grouping and summarising</a></li>
<li class="chapter" data-level="4.11" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#dw1-a9"><i class="fa fa-check"></i><b>4.11</b> Activity 9: Pipes</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html"><i class="fa fa-check"></i><b>5</b> Data wrangling 2</a>
<ul>
<li class="chapter" data-level="5.1" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#learning-to-wrangle-is-there-a-chastity-belt-on-perception"><i class="fa fa-check"></i><b>5.1</b> Learning to wrangle: Is there a chastity belt on perception</a></li>
<li class="chapter" data-level="5.2" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#dw2-a1"><i class="fa fa-check"></i><b>5.2</b> Activity 1: Set-up Data Wrangling 2</a></li>
<li class="chapter" data-level="5.3" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#dw2-a2"><i class="fa fa-check"></i><b>5.3</b> Activity 2: Look at your data</a></li>
<li class="chapter" data-level="5.4" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#dw2-a3"><i class="fa fa-check"></i><b>5.4</b> Activity 3: <strong><code>select()</code></strong></a></li>
<li class="chapter" data-level="5.5" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#dw2-a4"><i class="fa fa-check"></i><b>5.5</b> Activity 4: Reorder the variables</a></li>
<li class="chapter" data-level="5.6" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#dw2-a5"><i class="fa fa-check"></i><b>5.6</b> Activity 5: <strong><code>arrange()</code></strong></a></li>
<li class="chapter" data-level="5.7" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#dw2-a6"><i class="fa fa-check"></i><b>5.7</b> Activity 6: <code>filter()</code></a></li>
<li class="chapter" data-level="5.8" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#dw2-a7"><i class="fa fa-check"></i><b>5.8</b> Activity 7: <code>mutate()</code></a></li>
<li class="chapter" data-level="5.9" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#dw2-a8"><i class="fa fa-check"></i><b>5.9</b> Activity 8: Summarising data</a></li>
<li class="chapter" data-level="5.10" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#dw2-a9"><i class="fa fa-check"></i><b>5.10</b> Activity 9: Counting observations</a></li>
<li class="chapter" data-level="5.11" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#dw2-bind"><i class="fa fa-check"></i><b>5.11</b> <code>bind_rows()</code></a></li>
<li class="chapter" data-level="5.12" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#dw2-pipes"><i class="fa fa-check"></i><b>5.12</b> Pipes (<strong><code>%&gt;%</code></strong>)</a>
<ul>
<li class="chapter" data-level="5.12.1" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#dw2-fin"><i class="fa fa-check"></i><b>5.12.1</b> Finished!</a></li>
</ul></li>
<li class="chapter" data-level="5.13" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#ds2-activity-solutions---data-wrangling-2"><i class="fa fa-check"></i><b>5.13</b> DS2 Activity solutions - Data wrangling 2</a>
<ul>
<li class="chapter" data-level="5.13.1" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#dw2-a3sol"><i class="fa fa-check"></i><b>5.13.1</b> Activity 3</a></li>
<li class="chapter" data-level="5.13.2" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#dw2-a4sol"><i class="fa fa-check"></i><b>5.13.2</b> Activity 4</a></li>
<li class="chapter" data-level="5.13.3" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#dw2-a5sol"><i class="fa fa-check"></i><b>5.13.3</b> Activity 5</a></li>
<li class="chapter" data-level="5.13.4" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#dw2-a6sol"><i class="fa fa-check"></i><b>5.13.4</b> Activity 6</a></li>
<li class="chapter" data-level="5.13.5" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#dw2-a7sol"><i class="fa fa-check"></i><b>5.13.5</b> Activity 7</a></li>
<li class="chapter" data-level="5.13.6" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#dw2-a8sol"><i class="fa fa-check"></i><b>5.13.6</b> Activity 8</a></li>
</ul></li>
<li class="chapter" data-level="5.14" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#dw2-debug"><i class="fa fa-check"></i><b>5.14</b> Debugging tips</a></li>
<li class="chapter" data-level="5.15" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#dw2-test"><i class="fa fa-check"></i><b>5.15</b> Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="data-wrangling-3.html"><a href="data-wrangling-3.html"><i class="fa fa-check"></i><b>6</b> Data Wrangling 3</a>
<ul>
<li class="chapter" data-level="6.1" data-path="data-wrangling-3.html"><a href="data-wrangling-3.html#data-wrangling-recap"><i class="fa fa-check"></i><b>6.1</b> Data wrangling recap</a></li>
<li class="chapter" data-level="6.2" data-path="data-wrangling-3.html"><a href="data-wrangling-3.html#tidy-data"><i class="fa fa-check"></i><b>6.2</b> Tidy data</a></li>
<li class="chapter" data-level="6.3" data-path="data-wrangling-3.html"><a href="data-wrangling-3.html#analysing-the-autism-spectrum-quotient-aq"><i class="fa fa-check"></i><b>6.3</b> Analysing the Autism Spectrum Quotient (AQ)</a></li>
<li class="chapter" data-level="6.4" data-path="data-wrangling-3.html"><a href="data-wrangling-3.html#dw3-a1"><i class="fa fa-check"></i><b>6.4</b> Activity 1: Set-up Data Wrangling 3</a></li>
<li class="chapter" data-level="6.5" data-path="data-wrangling-3.html"><a href="data-wrangling-3.html#dw3-a2"><i class="fa fa-check"></i><b>6.5</b> Activity 2: Load in the data</a></li>
<li class="chapter" data-level="6.6" data-path="data-wrangling-3.html"><a href="data-wrangling-3.html#dw3-a3"><i class="fa fa-check"></i><b>6.6</b> Activity 3: Look at your data</a></li>
<li class="chapter" data-level="6.7" data-path="data-wrangling-3.html"><a href="data-wrangling-3.html#dw3-a4"><i class="fa fa-check"></i><b>6.7</b> Activity 4: Tidying data</a></li>
<li class="chapter" data-level="6.8" data-path="data-wrangling-3.html"><a href="data-wrangling-3.html#dw3-a5"><i class="fa fa-check"></i><b>6.8</b> Activity 5: Combining data</a></li>
<li class="chapter" data-level="6.9" data-path="data-wrangling-3.html"><a href="data-wrangling-3.html#dw3-a6"><i class="fa fa-check"></i><b>6.9</b> Activity 6: Combining more data</a></li>
<li class="chapter" data-level="6.10" data-path="data-wrangling-3.html"><a href="data-wrangling-3.html#dw3-a7"><i class="fa fa-check"></i><b>6.10</b> Activity 7: Calculating the AQ scores</a></li>
<li class="chapter" data-level="6.11" data-path="data-wrangling-3.html"><a href="data-wrangling-3.html#dw3-a8"><i class="fa fa-check"></i><b>6.11</b> Activity 8: One last thing on pipes</a></li>
<li class="chapter" data-level="6.12" data-path="data-wrangling-3.html"><a href="data-wrangling-3.html#dw3-sols"><i class="fa fa-check"></i><b>6.12</b> Activity solutions</a>
<ul>
<li class="chapter" data-level="6.12.1" data-path="data-wrangling-3.html"><a href="data-wrangling-3.html#dw3-a2sol"><i class="fa fa-check"></i><b>6.12.1</b> Activity 2</a></li>
<li class="chapter" data-level="6.12.2" data-path="data-wrangling-3.html"><a href="data-wrangling-3.html#dw3-a5sol"><i class="fa fa-check"></i><b>6.12.2</b> Activity 5</a></li>
<li class="chapter" data-level="6.12.3" data-path="data-wrangling-3.html"><a href="data-wrangling-3.html#dw3-a7sol"><i class="fa fa-check"></i><b>6.12.3</b> Activity 7</a></li>
<li class="chapter" data-level="6.12.4" data-path="data-wrangling-3.html"><a href="data-wrangling-3.html#dw3-a8sol"><i class="fa fa-check"></i><b>6.12.4</b> Activity 8</a></li>
</ul></li>
<li class="chapter" data-level="6.13" data-path="data-wrangling-3.html"><a href="data-wrangling-3.html#dw3-test"><i class="fa fa-check"></i><b>6.13</b> Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="intro-to-data-viz.html"><a href="intro-to-data-viz.html"><i class="fa fa-check"></i><b>7</b> Intro to Data Viz</a>
<ul>
<li class="chapter" data-level="7.1" data-path="intro-to-data-viz.html"><a href="intro-to-data-viz.html#introviz-a1"><i class="fa fa-check"></i><b>7.1</b> Activity 1: dplyr recap</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="intro-to-data-viz.html"><a href="intro-to-data-viz.html#data-visualisation"><i class="fa fa-check"></i><b>7.1.1</b> Data visualisation</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="intro-to-data-viz.html"><a href="intro-to-data-viz.html#introviz-a2"><i class="fa fa-check"></i><b>7.2</b> Activity 2: Set-up</a></li>
<li class="chapter" data-level="7.3" data-path="intro-to-data-viz.html"><a href="intro-to-data-viz.html#introviz-a3"><i class="fa fa-check"></i><b>7.3</b> Activity 3: Factors</a></li>
<li class="chapter" data-level="7.4" data-path="intro-to-data-viz.html"><a href="intro-to-data-viz.html#introviz-a4"><i class="fa fa-check"></i><b>7.4</b> Activity 4: Bar plot</a></li>
<li class="chapter" data-level="7.5" data-path="intro-to-data-viz.html"><a href="intro-to-data-viz.html#introviz-a5"><i class="fa fa-check"></i><b>7.5</b> Activity 5: Violin-boxplot</a></li>
<li class="chapter" data-level="7.6" data-path="intro-to-data-viz.html"><a href="intro-to-data-viz.html#introviz-a6"><i class="fa fa-check"></i><b>7.6</b> Activity 6: Layers part 2</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="intro-to-data-viz.html"><a href="intro-to-data-viz.html#introviz-fin"><i class="fa fa-check"></i><b>7.6.1</b> Finished!</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>8</b> Probability</a>
<ul>
<li class="chapter" data-level="8.1" data-path="probability.html"><a href="probability.html#prob-a1"><i class="fa fa-check"></i><b>8.1</b> Activity 1: Prep</a></li>
<li class="chapter" data-level="8.2" data-path="probability.html"><a href="probability.html#what-is-probability"><i class="fa fa-check"></i><b>8.2</b> What is probability?</a></li>
<li class="chapter" data-level="8.3" data-path="probability.html"><a href="probability.html#types-of-data"><i class="fa fa-check"></i><b>8.3</b> Types of data</a></li>
<li class="chapter" data-level="8.4" data-path="probability.html"><a href="probability.html#prob-a2"><i class="fa fa-check"></i><b>8.4</b> Activity 2: Types of data</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="probability.html"><a href="probability.html#probability-distributions"><i class="fa fa-check"></i><b>8.4.1</b> Probability distributions</a></li>
<li class="chapter" data-level="8.4.2" data-path="probability.html"><a href="probability.html#the-uniform-distribution"><i class="fa fa-check"></i><b>8.4.2</b> The uniform distribution</a></li>
<li class="chapter" data-level="8.4.3" data-path="probability.html"><a href="probability.html#the-binomial-distribution"><i class="fa fa-check"></i><b>8.4.3</b> The binomial distribution</a></li>
<li class="chapter" data-level="8.4.4" data-path="probability.html"><a href="probability.html#the-normal-distribution"><i class="fa fa-check"></i><b>8.4.4</b> The normal distribution</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="probability.html"><a href="probability.html#prob-a3"><i class="fa fa-check"></i><b>8.5</b> Activity 3: Normal distribution</a></li>
<li class="chapter" data-level="8.6" data-path="probability.html"><a href="probability.html#prob-a4"><i class="fa fa-check"></i><b>8.6</b> Activity 4: Distribution test</a></li>
<li class="chapter" data-level="8.7" data-path="probability.html"><a href="probability.html#prob-a5"><i class="fa fa-check"></i><b>8.7</b> Activity 5: Binomial distribution</a></li>
<li class="chapter" data-level="8.8" data-path="probability.html"><a href="probability.html#prob-a6"><i class="fa fa-check"></i><b>8.8</b> Activity 6: <code>dbinom()</code></a></li>
<li class="chapter" data-level="8.9" data-path="probability.html"><a href="probability.html#prob-a7"><i class="fa fa-check"></i><b>8.9</b> Activity 7: <code>pbinom()</code></a></li>
<li class="chapter" data-level="8.10" data-path="probability.html"><a href="probability.html#prob-a8"><i class="fa fa-check"></i><b>8.10</b> Activity 8: <code>pbinom()</code> 2</a></li>
<li class="chapter" data-level="8.11" data-path="probability.html"><a href="probability.html#prob-a9"><i class="fa fa-check"></i><b>8.11</b> Activity 9: <code>qbinom()</code></a></li>
<li class="chapter" data-level="8.12" data-path="probability.html"><a href="probability.html#normal-distribution"><i class="fa fa-check"></i><b>8.12</b> Normal distribution</a>
<ul>
<li class="chapter" data-level="8.12.1" data-path="probability.html"><a href="probability.html#probability-of-heights"><i class="fa fa-check"></i><b>8.12.1</b> Probability of heights</a></li>
</ul></li>
<li class="chapter" data-level="8.13" data-path="probability.html"><a href="probability.html#prob-a10"><i class="fa fa-check"></i><b>8.13</b> Activity 10:<code>pnorm()</code></a></li>
<li class="chapter" data-level="8.14" data-path="probability.html"><a href="probability.html#prob-a11"><i class="fa fa-check"></i><b>8.14</b> Activity 11: <code>pnorm</code> 2</a></li>
<li class="chapter" data-level="8.15" data-path="probability.html"><a href="probability.html#prob-a12"><i class="fa fa-check"></i><b>8.15</b> Activity 12: <code>pnorm</code> 3</a></li>
<li class="chapter" data-level="8.16" data-path="probability.html"><a href="probability.html#prob-a13"><i class="fa fa-check"></i><b>8.16</b> Activity 13: <code>qnorm()</code></a></li>
<li class="chapter" data-level="8.17" data-path="probability.html"><a href="probability.html#prob-sols"><i class="fa fa-check"></i><b>8.17</b> Activity solutions</a>
<ul>
<li class="chapter" data-level="8.17.1" data-path="probability.html"><a href="probability.html#prob-a6sol"><i class="fa fa-check"></i><b>8.17.1</b> Activity 6</a></li>
<li class="chapter" data-level="8.17.2" data-path="probability.html"><a href="probability.html#prob-a7sol"><i class="fa fa-check"></i><b>8.17.2</b> Activity 7</a></li>
<li class="chapter" data-level="8.17.3" data-path="probability.html"><a href="probability.html#prob-a8sol"><i class="fa fa-check"></i><b>8.17.3</b> Activity 8</a></li>
<li class="chapter" data-level="8.17.4" data-path="probability.html"><a href="probability.html#prob-a10sol"><i class="fa fa-check"></i><b>8.17.4</b> Activity 10</a></li>
<li class="chapter" data-level="8.17.5" data-path="probability.html"><a href="probability.html#prob-a11sol"><i class="fa fa-check"></i><b>8.17.5</b> Activity 11</a></li>
<li class="chapter" data-level="8.17.6" data-path="probability.html"><a href="probability.html#prob-a12sol"><i class="fa fa-check"></i><b>8.17.6</b> Activity 12</a></li>
<li class="chapter" data-level="8.17.7" data-path="probability.html"><a href="probability.html#prob-a13sol"><i class="fa fa-check"></i><b>8.17.7</b> Activity 13</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="correlation.html"><a href="correlation.html"><i class="fa fa-check"></i><b>9</b> Correlation</a>
<ul>
<li class="chapter" data-level="9.1" data-path="correlation.html"><a href="correlation.html#correlation-1"><i class="fa fa-check"></i><b>9.1</b> Correlation</a></li>
<li class="chapter" data-level="9.2" data-path="correlation.html"><a href="correlation.html#corr-a1"><i class="fa fa-check"></i><b>9.2</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="9.3" data-path="correlation.html"><a href="correlation.html#corr-a2"><i class="fa fa-check"></i><b>9.3</b> Activity 2: Look at your data</a></li>
<li class="chapter" data-level="9.4" data-path="correlation.html"><a href="correlation.html#corr-a3"><i class="fa fa-check"></i><b>9.4</b> Activity 3: Assumptions</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="correlation.html"><a href="correlation.html#assumption-1-level-of-measurement"><i class="fa fa-check"></i><b>9.4.1</b> Assumption 1: Level of Measurement</a></li>
<li class="chapter" data-level="9.4.2" data-path="correlation.html"><a href="correlation.html#assumption-2-pairs-of-data"><i class="fa fa-check"></i><b>9.4.2</b> Assumption 2: Pairs of Data</a></li>
<li class="chapter" data-level="9.4.3" data-path="correlation.html"><a href="correlation.html#assumption-3-5-normality-linearity-homoscedasticity"><i class="fa fa-check"></i><b>9.4.3</b> Assumption 3-5: Normality, linearity, homoscedasticity</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="correlation.html"><a href="correlation.html#correlation-scatterplot"><i class="fa fa-check"></i><b>9.5</b> Correlation Scatterplot</a></li>
<li class="chapter" data-level="9.6" data-path="correlation.html"><a href="correlation.html#corr-a4"><i class="fa fa-check"></i><b>9.6</b> Activity 4: Descriptive statistics</a></li>
<li class="chapter" data-level="9.7" data-path="correlation.html"><a href="correlation.html#corr-a5"><i class="fa fa-check"></i><b>9.7</b> Activity 5: Run the correlation</a></li>
<li class="chapter" data-level="9.8" data-path="correlation.html"><a href="correlation.html#corr-a6"><i class="fa fa-check"></i><b>9.8</b> Activity 6: Interpreting the correlation</a></li>
<li class="chapter" data-level="9.9" data-path="correlation.html"><a href="correlation.html#corr-a7"><i class="fa fa-check"></i><b>9.9</b> Activity 7: Write-up</a></li>
<li class="chapter" data-level="9.10" data-path="correlation.html"><a href="correlation.html#corr-a8"><i class="fa fa-check"></i><b>9.10</b> Activity 8: Scatterplot matrix</a></li>
<li class="chapter" data-level="9.11" data-path="correlation.html"><a href="correlation.html#corr-a9"><i class="fa fa-check"></i><b>9.11</b> Activity 9: Multiple correlations</a></li>
<li class="chapter" data-level="9.12" data-path="correlation.html"><a href="correlation.html#corr-fin"><i class="fa fa-check"></i><b>9.12</b> Finished!</a></li>
<li class="chapter" data-level="9.13" data-path="correlation.html"><a href="correlation.html#corr-sols"><i class="fa fa-check"></i><b>9.13</b> Activity solutions</a>
<ul>
<li class="chapter" data-level="9.13.1" data-path="correlation.html"><a href="correlation.html#corr-a1sol"><i class="fa fa-check"></i><b>9.13.1</b> Activity 1</a></li>
<li class="chapter" data-level="9.13.2" data-path="correlation.html"><a href="correlation.html#corr-a3sol"><i class="fa fa-check"></i><b>9.13.2</b> Activity 3</a></li>
<li class="chapter" data-level="9.13.3" data-path="correlation.html"><a href="correlation.html#corr-a4sol"><i class="fa fa-check"></i><b>9.13.3</b> Activity 4</a></li>
<li class="chapter" data-level="9.13.4" data-path="correlation.html"><a href="correlation.html#corr-a5sol"><i class="fa fa-check"></i><b>9.13.4</b> Activity 5</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="t-tests.html"><a href="t-tests.html"><i class="fa fa-check"></i><b>10</b> t-tests</a>
<ul>
<li class="chapter" data-level="10.1" data-path="t-tests.html"><a href="t-tests.html#ttest-a1"><i class="fa fa-check"></i><b>10.1</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="10.2" data-path="t-tests.html"><a href="t-tests.html#ttest-a2"><i class="fa fa-check"></i><b>10.2</b> Activity 2: Explore the dataset</a></li>
<li class="chapter" data-level="10.3" data-path="t-tests.html"><a href="t-tests.html#ttest-a3"><i class="fa fa-check"></i><b>10.3</b> Activity 3: Ratings</a></li>
<li class="chapter" data-level="10.4" data-path="t-tests.html"><a href="t-tests.html#ttest-a4"><i class="fa fa-check"></i><b>10.4</b> Activity 4: Visualisation</a></li>
<li class="chapter" data-level="10.5" data-path="t-tests.html"><a href="t-tests.html#ttest-a5"><i class="fa fa-check"></i><b>10.5</b> Activity 5: Assumptions</a></li>
<li class="chapter" data-level="10.6" data-path="t-tests.html"><a href="t-tests.html#ttest-a6"><i class="fa fa-check"></i><b>10.6</b> Activity 6: Running the t-test</a></li>
<li class="chapter" data-level="10.7" data-path="t-tests.html"><a href="t-tests.html#ttest-a7"><i class="fa fa-check"></i><b>10.7</b> Activity 7: Correcting for multiple comparisons</a></li>
<li class="chapter" data-level="10.8" data-path="t-tests.html"><a href="t-tests.html#ttest-a8"><i class="fa fa-check"></i><b>10.8</b> Activity 8: Effect size</a></li>
<li class="chapter" data-level="10.9" data-path="t-tests.html"><a href="t-tests.html#ttest-a9"><i class="fa fa-check"></i><b>10.9</b> Activity 9: Interpreting the results</a></li>
<li class="chapter" data-level="10.10" data-path="t-tests.html"><a href="t-tests.html#ttest-a10"><i class="fa fa-check"></i><b>10.10</b> Activity 10: Write-up</a></li>
<li class="chapter" data-level="10.11" data-path="t-tests.html"><a href="t-tests.html#ttest-a11"><i class="fa fa-check"></i><b>10.11</b> Activity 11: Paired-samples t-test</a></li>
<li class="chapter" data-level="10.12" data-path="t-tests.html"><a href="t-tests.html#ttest-a12"><i class="fa fa-check"></i><b>10.12</b> Activity 12: Assumptions</a></li>
<li class="chapter" data-level="10.13" data-path="t-tests.html"><a href="t-tests.html#ttest-a13"><i class="fa fa-check"></i><b>10.13</b> Activity 13: Descriptives and visualisations</a></li>
<li class="chapter" data-level="10.14" data-path="t-tests.html"><a href="t-tests.html#ttest-a14"><i class="fa fa-check"></i><b>10.14</b> Activity 14: Paired-samples t-test</a></li>
<li class="chapter" data-level="10.15" data-path="t-tests.html"><a href="t-tests.html#ttest-a15"><i class="fa fa-check"></i><b>10.15</b> Activity 15: Write-up</a>
<ul>
<li class="chapter" data-level="10.15.1" data-path="t-tests.html"><a href="t-tests.html#ttest-fin"><i class="fa fa-check"></i><b>10.15.1</b> Finished!</a></li>
</ul></li>
<li class="chapter" data-level="10.16" data-path="t-tests.html"><a href="t-tests.html#ttest-sols"><i class="fa fa-check"></i><b>10.16</b> Activity solutions</a>
<ul>
<li class="chapter" data-level="10.16.1" data-path="t-tests.html"><a href="t-tests.html#ttest-a1sol"><i class="fa fa-check"></i><b>10.16.1</b> Activity 1</a></li>
<li class="chapter" data-level="10.16.2" data-path="t-tests.html"><a href="t-tests.html#ttest-a2sol"><i class="fa fa-check"></i><b>10.16.2</b> Activity 2</a></li>
<li class="chapter" data-level="10.16.3" data-path="t-tests.html"><a href="t-tests.html#ttest-a6sol"><i class="fa fa-check"></i><b>10.16.3</b> Activity 6</a></li>
<li class="chapter" data-level="10.16.4" data-path="t-tests.html"><a href="t-tests.html#ttest-a8sol"><i class="fa fa-check"></i><b>10.16.4</b> Activity 8</a></li>
<li class="chapter" data-level="10.16.5" data-path="t-tests.html"><a href="t-tests.html#ttest-a12sol"><i class="fa fa-check"></i><b>10.16.5</b> Activity 12</a></li>
<li class="chapter" data-level="10.16.6" data-path="t-tests.html"><a href="t-tests.html#ttest-a13sol"><i class="fa fa-check"></i><b>10.16.6</b> Activity 13</a></li>
<li class="chapter" data-level="10.16.7" data-path="t-tests.html"><a href="t-tests.html#ttest-a14sol"><i class="fa fa-check"></i><b>10.16.7</b> Activity 14</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="power-and-error.html"><a href="power-and-error.html"><i class="fa fa-check"></i><b>11</b> Power and error</a>
<ul>
<li class="chapter" data-level="11.1" data-path="power-and-error.html"><a href="power-and-error.html#effect-size"><i class="fa fa-check"></i><b>11.1</b> Effect Size</a></li>
<li class="chapter" data-level="11.2" data-path="power-and-error.html"><a href="power-and-error.html#power-a1"><i class="fa fa-check"></i><b>11.2</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="11.3" data-path="power-and-error.html"><a href="power-and-error.html#power-a2"><i class="fa fa-check"></i><b>11.3</b> Activity 2: Effect size from a one-sample t-test</a></li>
<li class="chapter" data-level="11.4" data-path="power-and-error.html"><a href="power-and-error.html#power-a3"><i class="fa fa-check"></i><b>11.4</b> Activity 3: Effect size from between-subjects t-test</a></li>
<li class="chapter" data-level="11.5" data-path="power-and-error.html"><a href="power-and-error.html#power-a4"><i class="fa fa-check"></i><b>11.5</b> Activity 4: t-value and effect size for a between-subjects Experiment</a></li>
<li class="chapter" data-level="11.6" data-path="power-and-error.html"><a href="power-and-error.html#power-a5"><i class="fa fa-check"></i><b>11.6</b> Activity 5: <code>pwr.t.test()</code></a></li>
<li class="chapter" data-level="11.7" data-path="power-and-error.html"><a href="power-and-error.html#power-a6"><i class="fa fa-check"></i><b>11.7</b> Activity 6: Sample size for standard power one-sample t-test</a></li>
<li class="chapter" data-level="11.8" data-path="power-and-error.html"><a href="power-and-error.html#pe-activity-7-effect-size-from-a-high-power-between-subjects-t-test"><i class="fa fa-check"></i><b>11.8</b> P&amp;E Activity 7: Effect size from a high power between-subjects t-test</a></li>
<li class="chapter" data-level="11.9" data-path="power-and-error.html"><a href="power-and-error.html#power-a8"><i class="fa fa-check"></i><b>11.9</b> Activity 8: Sample size for a correlation</a></li>
<li class="chapter" data-level="11.10" data-path="power-and-error.html"><a href="power-and-error.html#power-a9"><i class="fa fa-check"></i><b>11.10</b> Activity 9: Effect size for a correlation analysis</a></li>
<li class="chapter" data-level="11.11" data-path="power-and-error.html"><a href="power-and-error.html#power-a10"><i class="fa fa-check"></i><b>11.11</b> Activity 10: Power of published research</a>
<ul>
<li class="chapter" data-level="11.11.1" data-path="power-and-error.html"><a href="power-and-error.html#power-fin"><i class="fa fa-check"></i><b>11.11.1</b> Finished!</a></li>
</ul></li>
<li class="chapter" data-level="11.12" data-path="power-and-error.html"><a href="power-and-error.html#power-sols"><i class="fa fa-check"></i><b>11.12</b> Activity solutions</a>
<ul>
<li class="chapter" data-level="11.12.1" data-path="power-and-error.html"><a href="power-and-error.html#power-a1sol"><i class="fa fa-check"></i><b>11.12.1</b> Activity 1</a></li>
<li class="chapter" data-level="11.12.2" data-path="power-and-error.html"><a href="power-and-error.html#power-a2sol"><i class="fa fa-check"></i><b>11.12.2</b> Activity 2</a></li>
<li class="chapter" data-level="11.12.3" data-path="power-and-error.html"><a href="power-and-error.html#power-a3sol"><i class="fa fa-check"></i><b>11.12.3</b> Activity 3</a></li>
<li class="chapter" data-level="11.12.4" data-path="power-and-error.html"><a href="power-and-error.html#power-a4sol"><i class="fa fa-check"></i><b>11.12.4</b> Activity 4</a></li>
<li class="chapter" data-level="11.12.5" data-path="power-and-error.html"><a href="power-and-error.html#power-a6sol"><i class="fa fa-check"></i><b>11.12.5</b> Activity 6</a></li>
<li class="chapter" data-level="11.12.6" data-path="power-and-error.html"><a href="power-and-error.html#power-a7sol"><i class="fa fa-check"></i><b>11.12.6</b> Activity 7</a></li>
<li class="chapter" data-level="11.12.7" data-path="power-and-error.html"><a href="power-and-error.html#power-a8sol"><i class="fa fa-check"></i><b>11.12.7</b> Activity 8</a></li>
<li class="chapter" data-level="11.12.8" data-path="power-and-error.html"><a href="power-and-error.html#power-a9sol"><i class="fa fa-check"></i><b>11.12.8</b> Activity 9</a></li>
<li class="chapter" data-level="11.12.9" data-path="power-and-error.html"><a href="power-and-error.html#power-a10sol"><i class="fa fa-check"></i><b>11.12.9</b> Activity 10</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="screening-data.html"><a href="screening-data.html"><i class="fa fa-check"></i><b>12</b> Screening Data</a>
<ul>
<li class="chapter" data-level="12.1" data-path="screening-data.html"><a href="screening-data.html#screening-a1"><i class="fa fa-check"></i><b>12.1</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="12.2" data-path="screening-data.html"><a href="screening-data.html#screening-a2"><i class="fa fa-check"></i><b>12.2</b> Activity 2: Look at the data</a></li>
<li class="chapter" data-level="12.3" data-path="screening-data.html"><a href="screening-data.html#missing-data"><i class="fa fa-check"></i><b>12.3</b> Missing data</a></li>
<li class="chapter" data-level="12.4" data-path="screening-data.html"><a href="screening-data.html#screening-a3"><i class="fa fa-check"></i><b>12.4</b> Activity 3: <code>summary()</code></a></li>
<li class="chapter" data-level="12.5" data-path="screening-data.html"><a href="screening-data.html#screening-a4"><i class="fa fa-check"></i><b>12.5</b> Activity 4: Listwise deletion</a></li>
<li class="chapter" data-level="12.6" data-path="screening-data.html"><a href="screening-data.html#pairwise-deletion"><i class="fa fa-check"></i><b>12.6</b> Pairwise deletion</a></li>
<li class="chapter" data-level="12.7" data-path="screening-data.html"><a href="screening-data.html#screening-a5"><i class="fa fa-check"></i><b>12.7</b> Activity 5: <code>na.rm = TRUE</code></a></li>
<li class="chapter" data-level="12.8" data-path="screening-data.html"><a href="screening-data.html#screening-a6"><i class="fa fa-check"></i><b>12.8</b> Activity 6: Implausible values</a></li>
<li class="chapter" data-level="12.9" data-path="screening-data.html"><a href="screening-data.html#screening-a7"><i class="fa fa-check"></i><b>12.9</b> Activity 7: Visualising implausible values</a></li>
<li class="chapter" data-level="12.10" data-path="screening-data.html"><a href="screening-data.html#dealing-with-implausible-values-or-missing-data"><i class="fa fa-check"></i><b>12.10</b> Dealing with implausible values or missing data</a></li>
<li class="chapter" data-level="12.11" data-path="screening-data.html"><a href="screening-data.html#alternative-descriptive-statistics"><i class="fa fa-check"></i><b>12.11</b> Alternative descriptive statistics</a></li>
<li class="chapter" data-level="12.12" data-path="screening-data.html"><a href="screening-data.html#screening-fin"><i class="fa fa-check"></i><b>12.12</b> Finished!</a></li>
<li class="chapter" data-level="12.13" data-path="screening-data.html"><a href="screening-data.html#screening-sols"><i class="fa fa-check"></i><b>12.13</b> Activity solutions</a>
<ul>
<li class="chapter" data-level="12.13.1" data-path="screening-data.html"><a href="screening-data.html#screening-a1sol"><i class="fa fa-check"></i><b>12.13.1</b> Activity 1</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="visualisation.html"><a href="visualisation.html"><i class="fa fa-check"></i><b>13</b> Visualisation</a>
<ul>
<li class="chapter" data-level="13.1" data-path="visualisation.html"><a href="visualisation.html#viz-a1"><i class="fa fa-check"></i><b>13.1</b> Activity 1: Set-up Visualisation</a></li>
<li class="chapter" data-level="13.2" data-path="visualisation.html"><a href="visualisation.html#viz-a2"><i class="fa fa-check"></i><b>13.2</b> Activity 2: Histograms</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="visualisation.html"><a href="visualisation.html#basic-histogram"><i class="fa fa-check"></i><b>13.2.1</b> Basic histogram</a></li>
<li class="chapter" data-level="13.2.2" data-path="visualisation.html"><a href="visualisation.html#colour-and-fill"><i class="fa fa-check"></i><b>13.2.2</b> Colour and fill</a></li>
<li class="chapter" data-level="13.2.3" data-path="visualisation.html"><a href="visualisation.html#axis-labels"><i class="fa fa-check"></i><b>13.2.3</b> Axis labels</a></li>
<li class="chapter" data-level="13.2.4" data-path="visualisation.html"><a href="visualisation.html#density-curve"><i class="fa fa-check"></i><b>13.2.4</b> Density curve</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="visualisation.html"><a href="visualisation.html#viz-a3"><i class="fa fa-check"></i><b>13.3</b> Activity 3: Scatterplots</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="visualisation.html"><a href="visualisation.html#basic-scatterplot"><i class="fa fa-check"></i><b>13.3.1</b> Basic scatterplot</a></li>
<li class="chapter" data-level="13.3.2" data-path="visualisation.html"><a href="visualisation.html#axis-labels-1"><i class="fa fa-check"></i><b>13.3.2</b> Axis labels</a></li>
<li class="chapter" data-level="13.3.3" data-path="visualisation.html"><a href="visualisation.html#adding-a-regression-line"><i class="fa fa-check"></i><b>13.3.3</b> Adding a regression line</a></li>
<li class="chapter" data-level="13.3.4" data-path="visualisation.html"><a href="visualisation.html#grouped-scatterplots"><i class="fa fa-check"></i><b>13.3.4</b> Grouped scatterplots</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="visualisation.html"><a href="visualisation.html#viz-a4"><i class="fa fa-check"></i><b>13.4</b> Activity 4: Boxplots</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="visualisation.html"><a href="visualisation.html#basic-boxplot"><i class="fa fa-check"></i><b>13.4.1</b> Basic boxplot</a></li>
<li class="chapter" data-level="13.4.2" data-path="visualisation.html"><a href="visualisation.html#adding-data-points"><i class="fa fa-check"></i><b>13.4.2</b> Adding data points</a></li>
<li class="chapter" data-level="13.4.3" data-path="visualisation.html"><a href="visualisation.html#adding-colour"><i class="fa fa-check"></i><b>13.4.3</b> Adding colour</a></li>
<li class="chapter" data-level="13.4.4" data-path="visualisation.html"><a href="visualisation.html#boxplots-for-multiple-factors"><i class="fa fa-check"></i><b>13.4.4</b> Boxplots for multiple factors</a></li>
<li class="chapter" data-level="13.4.5" data-path="visualisation.html"><a href="visualisation.html#colour-blind-friendly-options"><i class="fa fa-check"></i><b>13.4.5</b> Colour-blind friendly options</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="visualisation.html"><a href="visualisation.html#viz-a5"><i class="fa fa-check"></i><b>13.5</b> Activity 5: Reordering factors</a></li>
<li class="chapter" data-level="13.6" data-path="visualisation.html"><a href="visualisation.html#viz-a6"><i class="fa fa-check"></i><b>13.6</b> Activity 6: Bar Charts</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="visualisation.html"><a href="visualisation.html#basic-bar-chart"><i class="fa fa-check"></i><b>13.6.1</b> Basic bar chart</a></li>
<li class="chapter" data-level="13.6.2" data-path="visualisation.html"><a href="visualisation.html#bar-charts-with-two-factors"><i class="fa fa-check"></i><b>13.6.2</b> Bar charts with two factors</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="visualisation.html"><a href="visualisation.html#viz-a7"><i class="fa fa-check"></i><b>13.7</b> Activity 7: Violin plots</a>
<ul>
<li class="chapter" data-level="13.7.1" data-path="visualisation.html"><a href="visualisation.html#basic-violin-plot"><i class="fa fa-check"></i><b>13.7.1</b> Basic violin plot</a></li>
<li class="chapter" data-level="13.7.2" data-path="visualisation.html"><a href="visualisation.html#violin-plots-with-raw-data-points"><i class="fa fa-check"></i><b>13.7.2</b> Violin plots with raw data points</a></li>
</ul></li>
<li class="chapter" data-level="13.8" data-path="visualisation.html"><a href="visualisation.html#viz-a8"><i class="fa fa-check"></i><b>13.8</b> Activity 8: Violin-boxplots</a></li>
<li class="chapter" data-level="13.9" data-path="visualisation.html"><a href="visualisation.html#viz-a9"><i class="fa fa-check"></i><b>13.9</b> Activity 9: Faceting</a>
<ul>
<li class="chapter" data-level="13.9.1" data-path="visualisation.html"><a href="visualisation.html#facet-labelling"><i class="fa fa-check"></i><b>13.9.1</b> Facet labelling</a></li>
</ul></li>
<li class="chapter" data-level="13.10" data-path="visualisation.html"><a href="visualisation.html#viz-a10"><i class="fa fa-check"></i><b>13.10</b> Activity 10: Split-violins and raincloud plots</a>
<ul>
<li class="chapter" data-level="13.10.1" data-path="visualisation.html"><a href="visualisation.html#split-violin-plots"><i class="fa fa-check"></i><b>13.10.1</b> Split-violin plots</a></li>
<li class="chapter" data-level="13.10.2" data-path="visualisation.html"><a href="visualisation.html#raincloud-plots"><i class="fa fa-check"></i><b>13.10.2</b> Raincloud plots</a></li>
<li class="chapter" data-level="13.10.3" data-path="visualisation.html"><a href="visualisation.html#raincloud-plots-with-multiple-factors"><i class="fa fa-check"></i><b>13.10.3</b> Raincloud plots with multiple factors</a></li>
<li class="chapter" data-level="13.10.4" data-path="visualisation.html"><a href="visualisation.html#viz-fin"><i class="fa fa-check"></i><b>13.10.4</b> Finished!</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="one-way-anova.html"><a href="one-way-anova.html"><i class="fa fa-check"></i><b>14</b> One-way ANOVA</a>
<ul>
<li class="chapter" data-level="14.0.1" data-path="one-way-anova.html"><a href="one-way-anova.html#background-intrusive-memories"><i class="fa fa-check"></i><b>14.0.1</b> Background: Intrusive memories</a></li>
<li class="chapter" data-level="14.0.2" data-path="one-way-anova.html"><a href="one-way-anova.html#anova-a1"><i class="fa fa-check"></i><b>14.0.2</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="14.0.3" data-path="one-way-anova.html"><a href="one-way-anova.html#anova-a2"><i class="fa fa-check"></i><b>14.0.3</b> Activity 2: Data wrangling</a></li>
<li class="chapter" data-level="14.0.4" data-path="one-way-anova.html"><a href="one-way-anova.html#anova-a3"><i class="fa fa-check"></i><b>14.0.4</b> Activity 3: Numbers and factors</a></li>
<li class="chapter" data-level="14.0.5" data-path="one-way-anova.html"><a href="one-way-anova.html#anova-a4"><i class="fa fa-check"></i><b>14.0.5</b> Activity 4: Create summary statistics</a></li>
<li class="chapter" data-level="14.0.6" data-path="one-way-anova.html"><a href="one-way-anova.html#anova-a5"><i class="fa fa-check"></i><b>14.0.6</b> Activity 5: Visualisation</a></li>
<li class="chapter" data-level="14.0.7" data-path="one-way-anova.html"><a href="one-way-anova.html#anova-a6"><i class="fa fa-check"></i><b>14.0.7</b> Activity 6: One-way ANOVA</a></li>
<li class="chapter" data-level="14.0.8" data-path="one-way-anova.html"><a href="one-way-anova.html#anova-a7"><i class="fa fa-check"></i><b>14.0.8</b> Activity 7: Assumption checking</a></li>
<li class="chapter" data-level="14.0.9" data-path="one-way-anova.html"><a href="one-way-anova.html#anova-a8"><i class="fa fa-check"></i><b>14.0.9</b> Activity 8: Post-hoc tests</a></li>
<li class="chapter" data-level="14.0.10" data-path="one-way-anova.html"><a href="one-way-anova.html#anova-a9"><i class="fa fa-check"></i><b>14.0.10</b> Activity 9: Power and effect size</a></li>
<li class="chapter" data-level="14.0.11" data-path="one-way-anova.html"><a href="one-way-anova.html#anova-a10"><i class="fa fa-check"></i><b>14.0.11</b> Activity 10: Write-up</a></li>
<li class="chapter" data-level="14.0.12" data-path="one-way-anova.html"><a href="one-way-anova.html#anova-sols"><i class="fa fa-check"></i><b>14.0.12</b> Activity solutions</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="factorial-anova.html"><a href="factorial-anova.html"><i class="fa fa-check"></i><b>15</b> Factorial ANOVA</a>
<ul>
<li class="chapter" data-level="15.0.1" data-path="factorial-anova.html"><a href="factorial-anova.html#factorial-a1"><i class="fa fa-check"></i><b>15.0.1</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="15.0.2" data-path="factorial-anova.html"><a href="factorial-anova.html#factorial-a2"><i class="fa fa-check"></i><b>15.0.2</b> Activity 2: Descriptive statistics</a></li>
<li class="chapter" data-level="15.0.3" data-path="factorial-anova.html"><a href="factorial-anova.html#factorial-a3"><i class="fa fa-check"></i><b>15.0.3</b> Activity 3: Violin-boxplots</a></li>
<li class="chapter" data-level="15.0.4" data-path="factorial-anova.html"><a href="factorial-anova.html#factorial-a4"><i class="fa fa-check"></i><b>15.0.4</b> Activity 4: Interaction plots</a></li>
<li class="chapter" data-level="15.0.5" data-path="factorial-anova.html"><a href="factorial-anova.html#factorial-a5"><i class="fa fa-check"></i><b>15.0.5</b> Activity 5: ANOVA</a></li>
<li class="chapter" data-level="15.0.6" data-path="factorial-anova.html"><a href="factorial-anova.html#factorial-a6"><i class="fa fa-check"></i><b>15.0.6</b> Activity 6: Assumption checking</a></li>
<li class="chapter" data-level="15.0.7" data-path="factorial-anova.html"><a href="factorial-anova.html#factorial-a7"><i class="fa fa-check"></i><b>15.0.7</b> Activity 7: Post-hoc tests</a></li>
<li class="chapter" data-level="15.0.8" data-path="factorial-anova.html"><a href="factorial-anova.html#factorial-a8"><i class="fa fa-check"></i><b>15.0.8</b> Activity 8: Write-up</a></li>
<li class="chapter" data-level="15.0.9" data-path="factorial-anova.html"><a href="factorial-anova.html#factorial-a9"><i class="fa fa-check"></i><b>15.0.9</b> Activity 9: Transforming data</a></li>
<li class="chapter" data-level="15.0.10" data-path="factorial-anova.html"><a href="factorial-anova.html#factorial-sols"><i class="fa fa-check"></i><b>15.0.10</b> Activity solutions</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>16</b> Regression</a>
<ul>
<li class="chapter" data-level="16.1" data-path="regression.html"><a href="regression.html#regression-a1"><i class="fa fa-check"></i><b>16.1</b> Activity 1: Setup</a></li>
<li class="chapter" data-level="16.2" data-path="regression.html"><a href="regression.html#regression-a2"><i class="fa fa-check"></i><b>16.2</b> Activity 2: Tidy the data</a></li>
<li class="chapter" data-level="16.3" data-path="regression.html"><a href="regression.html#regression-a3"><i class="fa fa-check"></i><b>16.3</b> Activity 3: Calculate mean anxiety for each student</a></li>
<li class="chapter" data-level="16.4" data-path="regression.html"><a href="regression.html#regression-a4"><i class="fa fa-check"></i><b>16.4</b> Activity 4: Join the datasets together</a></li>
<li class="chapter" data-level="16.5" data-path="regression.html"><a href="regression.html#regression-a5"><i class="fa fa-check"></i><b>16.5</b> Activity 5: Calculate descriptives for the variables overall</a></li>
<li class="chapter" data-level="16.6" data-path="regression.html"><a href="regression.html#regression-a6"><i class="fa fa-check"></i><b>16.6</b> Activity 6: Visualisations</a></li>
<li class="chapter" data-level="16.7" data-path="regression.html"><a href="regression.html#regression-a7"><i class="fa fa-check"></i><b>16.7</b> Activity 7: Run the regression</a></li>
<li class="chapter" data-level="16.8" data-path="regression.html"><a href="regression.html#regression-a8"><i class="fa fa-check"></i><b>16.8</b> Activity 8: Assumption checking</a></li>
<li class="chapter" data-level="16.9" data-path="regression.html"><a href="regression.html#regression-a9"><i class="fa fa-check"></i><b>16.9</b> Activity 9: Power and effect size</a></li>
<li class="chapter" data-level="16.10" data-path="regression.html"><a href="regression.html#regression-a10"><i class="fa fa-check"></i><b>16.10</b> Activity 10: Write-up</a></li>
<li class="chapter" data-level="16.11" data-path="regression.html"><a href="regression.html#regression-sols"><i class="fa fa-check"></i><b>16.11</b> Activity solutions</a>
<ul>
<li class="chapter" data-level="16.11.1" data-path="regression.html"><a href="regression.html#regression-a1sol"><i class="fa fa-check"></i><b>16.11.1</b> Activity 1</a></li>
<li class="chapter" data-level="16.11.2" data-path="regression.html"><a href="regression.html#regression-a2sol"><i class="fa fa-check"></i><b>16.11.2</b> Activity 2</a></li>
<li class="chapter" data-level="16.11.3" data-path="regression.html"><a href="regression.html#regression-a3sol"><i class="fa fa-check"></i><b>16.11.3</b> Activity 3</a></li>
<li class="chapter" data-level="16.11.4" data-path="regression.html"><a href="regression.html#regression-a4sol"><i class="fa fa-check"></i><b>16.11.4</b> Activity 4</a></li>
<li class="chapter" data-level="16.11.5" data-path="regression.html"><a href="regression.html#regression-a5sol"><i class="fa fa-check"></i><b>16.11.5</b> Activity 5</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>17</b> Multiple regression</a>
<ul>
<li class="chapter" data-level="17.1" data-path="multiple-regression.html"><a href="multiple-regression.html#mulregression-a1"><i class="fa fa-check"></i><b>17.1</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="17.2" data-path="multiple-regression.html"><a href="multiple-regression.html#mulregression-a2"><i class="fa fa-check"></i><b>17.2</b> Activity 2: Look at the data</a></li>
<li class="chapter" data-level="17.3" data-path="multiple-regression.html"><a href="multiple-regression.html#mulregression-a3"><i class="fa fa-check"></i><b>17.3</b> Activity 3: Compute the well-being score for each respondent</a></li>
<li class="chapter" data-level="17.4" data-path="multiple-regression.html"><a href="multiple-regression.html#mulregression-a4"><i class="fa fa-check"></i><b>17.4</b> Activity 4: Visualise the relationship</a></li>
<li class="chapter" data-level="17.5" data-path="multiple-regression.html"><a href="multiple-regression.html#mulregression-a5"><i class="fa fa-check"></i><b>17.5</b> Activity 5: Smartphone and well-being for boys and girls</a></li>
<li class="chapter" data-level="17.6" data-path="multiple-regression.html"><a href="multiple-regression.html#mulregression-a6"><i class="fa fa-check"></i><b>17.6</b> Activity 6: Mean-centering variables</a></li>
<li class="chapter" data-level="17.7" data-path="multiple-regression.html"><a href="multiple-regression.html#mulregression-a7"><i class="fa fa-check"></i><b>17.7</b> Activity 7: Visualise the relationship</a></li>
<li class="chapter" data-level="17.8" data-path="multiple-regression.html"><a href="multiple-regression.html#mulregression-a8"><i class="fa fa-check"></i><b>17.8</b> Activity 8: Running the regression</a></li>
<li class="chapter" data-level="17.9" data-path="multiple-regression.html"><a href="multiple-regression.html#mulregression-a9"><i class="fa fa-check"></i><b>17.9</b> Activity 9: Assumption checking</a></li>
<li class="chapter" data-level="17.10" data-path="multiple-regression.html"><a href="multiple-regression.html#mulregression-a10"><i class="fa fa-check"></i><b>17.10</b> Activity 10: Power and effect size</a></li>
<li class="chapter" data-level="17.11" data-path="multiple-regression.html"><a href="multiple-regression.html#mulregression-a11"><i class="fa fa-check"></i><b>17.11</b> Activity 11: Write-up</a></li>
<li class="chapter" data-level="17.12" data-path="multiple-regression.html"><a href="multiple-regression.html#mulregression-fin"><i class="fa fa-check"></i><b>17.12</b> Finished!</a></li>
<li class="chapter" data-level="17.13" data-path="multiple-regression.html"><a href="multiple-regression.html#mulregression-sols"><i class="fa fa-check"></i><b>17.13</b> Activity solutions</a>
<ul>
<li class="chapter" data-level="17.13.1" data-path="multiple-regression.html"><a href="multiple-regression.html#mulregression-a3sol"><i class="fa fa-check"></i><b>17.13.1</b> Activity 3</a></li>
<li class="chapter" data-level="17.13.2" data-path="multiple-regression.html"><a href="multiple-regression.html#mulregression-a5sol"><i class="fa fa-check"></i><b>17.13.2</b> Activity 5</a></li>
<li class="chapter" data-level="17.13.3" data-path="multiple-regression.html"><a href="multiple-regression.html#mulregression-a6sol"><i class="fa fa-check"></i><b>17.13.3</b> Activity 6</a></li>
<li class="chapter" data-level="17.13.4" data-path="multiple-regression.html"><a href="multiple-regression.html#mulregression-a7sol"><i class="fa fa-check"></i><b>17.13.4</b> Activity 7</a></li>
<li class="chapter" data-level="17.13.5" data-path="multiple-regression.html"><a href="multiple-regression.html#mulregression-a8sol"><i class="fa fa-check"></i><b>17.13.5</b> Activity 8</a></li>
<li class="chapter" data-level="17.13.6" data-path="multiple-regression.html"><a href="multiple-regression.html#mulregression-a9sol"><i class="fa fa-check"></i><b>17.13.6</b> Activity 9</a></li>
<li class="chapter" data-level="17.13.7" data-path="multiple-regression.html"><a href="multiple-regression.html#mulregression-a10sol"><i class="fa fa-check"></i><b>17.13.7</b> Activity 10</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="exporting-files-from-the-server.html"><a href="exporting-files-from-the-server.html"><i class="fa fa-check"></i><b>A</b> Exporting files from the server</a></li>
<li class="chapter" data-level="B" data-path="installing-r.html"><a href="installing-r.html"><i class="fa fa-check"></i><b>B</b> Installing R</a>
<ul>
<li class="chapter" data-level="B.0.1" data-path="installing-r.html"><a href="installing-r.html#why-should-i-install-r-on-my-computer"><i class="fa fa-check"></i><b>B.0.1</b> Why should I install R on my computer?</a></li>
<li class="chapter" data-level="B.0.2" data-path="installing-r.html"><a href="installing-r.html#windows"><i class="fa fa-check"></i><b>B.0.2</b> Windows</a></li>
<li class="chapter" data-level="B.0.3" data-path="installing-r.html"><a href="installing-r.html#mac"><i class="fa fa-check"></i><b>B.0.3</b> Mac</a></li>
<li class="chapter" data-level="B.0.4" data-path="installing-r.html"><a href="installing-r.html#chromebooks"><i class="fa fa-check"></i><b>B.0.4</b> Chromebooks</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="updating-r-rstudio-and-packages.html"><a href="updating-r-rstudio-and-packages.html"><i class="fa fa-check"></i><b>C</b> Updating R, RStudio, and packages</a>
<ul>
<li class="chapter" data-level="C.0.1" data-path="updating-r-rstudio-and-packages.html"><a href="updating-r-rstudio-and-packages.html#updating-rstudio"><i class="fa fa-check"></i><b>C.0.1</b> Updating RStudio</a></li>
<li class="chapter" data-level="C.1" data-path="updating-r-rstudio-and-packages.html"><a href="updating-r-rstudio-and-packages.html#updating-packages"><i class="fa fa-check"></i><b>C.1</b> Updating packages</a></li>
<li class="chapter" data-level="C.2" data-path="updating-r-rstudio-and-packages.html"><a href="updating-r-rstudio-and-packages.html#updating-r"><i class="fa fa-check"></i><b>C.2</b> Updating R</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="additional-r-resources.html"><a href="additional-r-resources.html"><i class="fa fa-check"></i><b>D</b> Additional R resources</a></li>
<li class="chapter" data-level="E" data-path="comparing-two-correlations.html"><a href="comparing-two-correlations.html"><i class="fa fa-check"></i><b>E</b> Comparing two correlations</a>
<ul>
<li class="chapter" data-level="E.0.1" data-path="comparing-two-correlations.html"><a href="comparing-two-correlations.html#compare-two-correlations-based-on-two-independent-groups"><i class="fa fa-check"></i><b>E.0.1</b> Compare two correlations based on two independent groups</a></li>
<li class="chapter" data-level="E.0.2" data-path="comparing-two-correlations.html"><a href="comparing-two-correlations.html#compare-two-overlapping-correlations-based-on-two-dependent-groups"><i class="fa fa-check"></i><b>E.0.2</b> Compare two overlapping correlations based on two dependent groups</a></li>
<li class="chapter" data-level="E.0.3" data-path="comparing-two-correlations.html"><a href="comparing-two-correlations.html#compare-two-non-overlapping-correlations-from-two-dependent-groups"><i class="fa fa-check"></i><b>E.0.3</b> Compare two non-overlapping correlations from two dependent groups</a></li>
</ul></li>
<li class="chapter" data-level="F" data-path="data-transformation.html"><a href="data-transformation.html"><i class="fa fa-check"></i><b>F</b> Data transformation</a></li>
<li class="chapter" data-level="G" data-path="permutation-tests.html"><a href="permutation-tests.html"><i class="fa fa-check"></i><b>G</b> Permutation tests</a>
<ul>
<li class="chapter" data-level="G.0.1" data-path="index.html"><a href="index.html#overview"><i class="fa fa-check"></i><b>G.0.1</b> Overview</a></li>
<li class="chapter" data-level="G.0.2" data-path="permutation-tests.html"><a href="permutation-tests.html#skill-1-generating-random-numbers"><i class="fa fa-check"></i><b>G.0.2</b> Skill 1: Generating Random Numbers</a></li>
<li class="chapter" data-level="G.0.3" data-path="permutation-tests.html"><a href="permutation-tests.html#skill-2-permuting-values"><i class="fa fa-check"></i><b>G.0.3</b> Skill 2: Permuting Values</a></li>
<li class="chapter" data-level="G.0.4" data-path="permutation-tests.html"><a href="permutation-tests.html#skill-3-creating-tibbles"><i class="fa fa-check"></i><b>G.0.4</b> Skill 3: Creating Tibbles</a></li>
<li class="chapter" data-level="G.0.5" data-path="permutation-tests.html"><a href="permutation-tests.html#entering-data-into-a-tibble"><i class="fa fa-check"></i><b>G.0.5</b> Entering Data into a Tibble</a></li>
<li class="chapter" data-level="G.0.6" data-path="permutation-tests.html"><a href="permutation-tests.html#repeating-values-to-save-typing"><i class="fa fa-check"></i><b>G.0.6</b> Repeating Values to Save Typing</a></li>
<li class="chapter" data-level="G.0.7" data-path="permutation-tests.html"><a href="permutation-tests.html#bringing-it-together-in-a-tibble"><i class="fa fa-check"></i><b>G.0.7</b> Bringing it Together in a Tibble</a></li>
<li class="chapter" data-level="G.0.8" data-path="permutation-tests.html"><a href="permutation-tests.html#skill-4-computing-differences-in-group-means"><i class="fa fa-check"></i><b>G.0.8</b> Skill 4: Computing Differences in Group Means</a></li>
<li class="chapter" data-level="G.0.9" data-path="permutation-tests.html"><a href="permutation-tests.html#skill-5-creating-your-own-functions"><i class="fa fa-check"></i><b>G.0.9</b> Skill 5: Creating Your Own Functions</a></li>
<li class="chapter" data-level="G.0.10" data-path="permutation-tests.html"><a href="permutation-tests.html#skill-6-replicating-operations"><i class="fa fa-check"></i><b>G.0.10</b> Skill 6: Replicating Operations</a></li>
<li class="chapter" data-level="G.0.11" data-path="intro-to-r.html"><a href="intro-to-r.html#finished"><i class="fa fa-check"></i><b>G.0.11</b> Finished!</a></li>
<li class="chapter" data-level="G.0.12" data-path="permutation-tests.html"><a href="permutation-tests.html#permutation-tests-of-hypotheses"><i class="fa fa-check"></i><b>G.0.12</b> Permutation Tests of Hypotheses</a></li>
<li class="chapter" data-level="G.0.13" data-path="permutation-tests.html"><a href="permutation-tests.html#Ch5InClassQueT1"><i class="fa fa-check"></i><b>G.0.13</b> Step 1: Load in Add-on Packages and Data</a></li>
<li class="chapter" data-level="G.0.14" data-path="permutation-tests.html"><a href="permutation-tests.html#Ch5InClassQueT2"><i class="fa fa-check"></i><b>G.0.14</b> Step 2: Calculate the Original Mean Difference - <span class="math inline">\(D_{orig}\)</span></a></li>
<li class="chapter" data-level="G.0.15" data-path="permutation-tests.html"><a href="permutation-tests.html#Ch5InClassQueT3"><i class="fa fa-check"></i><b>G.0.15</b> Step 3: Permute the Group Labels</a></li>
<li class="chapter" data-level="G.0.16" data-path="permutation-tests.html"><a href="permutation-tests.html#Ch5InClassQueT4"><i class="fa fa-check"></i><b>G.0.16</b> Step 4: Create the Null-Hypothesis Distribution (NHD) for the Difference</a></li>
<li class="chapter" data-level="G.0.17" data-path="permutation-tests.html"><a href="permutation-tests.html#Ch5InClassQueT5"><i class="fa fa-check"></i><b>G.0.17</b> Step 5: Compare the Observed Mean Difference to the NHD</a></li>
<li class="chapter" data-level="G.0.18" data-path="permutation-tests.html"><a href="permutation-tests.html#finished-1"><i class="fa fa-check"></i><b>G.0.18</b> Finished!</a></li>
</ul></li>
<li class="chapter" data-level="H" data-path="non-parametric-tests.html"><a href="non-parametric-tests.html"><i class="fa fa-check"></i><b>H</b> Non-parametric tests</a></li>
<li class="chapter" data-level="I" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html"><i class="fa fa-check"></i><b>I</b> Dissertation analysis guide</a>
<ul>
<li class="chapter" data-level="I.0.1" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#before-r"><i class="fa fa-check"></i><b>I.0.1</b> Before R</a></li>
<li class="chapter" data-level="I.0.2" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#study-design"><i class="fa fa-check"></i><b>I.0.2</b> Study design</a></li>
<li class="chapter" data-level="I.0.3" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#data-wrangling-considerations"><i class="fa fa-check"></i><b>I.0.3</b> Data wrangling considerations</a></li>
<li class="chapter" data-level="I.0.4" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#data-analysis"><i class="fa fa-check"></i><b>I.0.4</b> Data analysis</a></li>
<li class="chapter" data-level="I.0.5" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#exploring-and-cleaning-your-data"><i class="fa fa-check"></i><b>I.0.5</b> Exploring and cleaning your data</a></li>
<li class="chapter" data-level="I.0.6" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#summary"><i class="fa fa-check"></i><b>I.0.6</b> <code>summary()</code></a></li>
<li class="chapter" data-level="I.0.7" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#visualisations"><i class="fa fa-check"></i><b>I.0.7</b> Visualisations</a></li>
<li class="chapter" data-level="I.0.8" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#renaming-variables"><i class="fa fa-check"></i><b>I.0.8</b> Renaming variables</a></li>
<li class="chapter" data-level="I.0.9" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#converting-to-factors"><i class="fa fa-check"></i><b>I.0.9</b> Converting to factors</a></li>
<li class="chapter" data-level="I.0.10" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#dropping-irrelevant-variables"><i class="fa fa-check"></i><b>I.0.10</b> Dropping irrelevant variables</a></li>
<li class="chapter" data-level="I.0.11" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#recoding-variables"><i class="fa fa-check"></i><b>I.0.11</b> Recoding variables</a></li>
<li class="chapter" data-level="I.0.12" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#exclude-participantsdata"><i class="fa fa-check"></i><b>I.0.12</b> Exclude participants/data</a></li>
<li class="chapter" data-level="I.0.13" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#reliability"><i class="fa fa-check"></i><b>I.0.13</b> Reliability</a></li>
<li class="chapter" data-level="I.0.14" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#transforming-data"><i class="fa fa-check"></i><b>I.0.14</b> Transforming data</a></li>
<li class="chapter" data-level="I.0.15" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#replace-missing-values"><i class="fa fa-check"></i><b>I.0.15</b> Replace missing values</a></li>
<li class="chapter" data-level="I.0.16" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#convert-implausible-values"><i class="fa fa-check"></i><b>I.0.16</b> Convert implausible values</a></li>
<li class="chapter" data-level="I.0.17" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#calculate-z-scores"><i class="fa fa-check"></i><b>I.0.17</b> Calculate z-scores</a></li>
<li class="chapter" data-level="I.0.18" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#log-transformation"><i class="fa fa-check"></i><b>I.0.18</b> Log transformation</a></li>
<li class="chapter" data-level="I.0.19" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#square-root"><i class="fa fa-check"></i><b>I.0.19</b> Square root</a></li>
<li class="chapter" data-level="I.0.20" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#calculating-new-variables"><i class="fa fa-check"></i><b>I.0.20</b> Calculating new variables</a></li>
<li class="chapter" data-level="I.0.21" data-path="data-wrangling-3.html"><a href="data-wrangling-3.html#tidy-data"><i class="fa fa-check"></i><b>I.0.21</b> Tidy data</a></li>
<li class="chapter" data-level="I.0.22" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#summarising-and-visualising-data"><i class="fa fa-check"></i><b>I.0.22</b> Summarising and visualising data</a></li>
<li class="chapter" data-level="I.0.23" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#descriptive-statistics"><i class="fa fa-check"></i><b>I.0.23</b> Descriptive statistics</a></li>
<li class="chapter" data-level="I.0.24" data-path="intro-to-data-viz.html"><a href="intro-to-data-viz.html#data-visualisation"><i class="fa fa-check"></i><b>I.0.24</b> Data visualisation</a></li>
<li class="chapter" data-level="I.0.25" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#inferential-statistics"><i class="fa fa-check"></i><b>I.0.25</b> Inferential statistics</a></li>
<li class="chapter" data-level="I.0.26" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#assumption-tests"><i class="fa fa-check"></i><b>I.0.26</b> Assumption tests</a></li>
</ul></li>
<li class="divider"></li>
<li><a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" 
    target="blank"><img alt="Creative Commons License" 
    style="border-width:0" 
    src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><li>
<li><a href="https://psyteachr.github.io/" target="blank">PsyTeachR</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MSc Conversion in Psychological Studies</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="t-tests" class="section level1" number="10">
<h1><span class="header-section-number">Chapter 10</span> t-tests</h1>
<p>Two-sample designs are very common as often we want to know whether there is a difference between groups on a particular variable. There are different types of two-sample designs depending on whether or not the two groups are independent (e.g. different participants on different conditions) or not (e.g. same participants on different conditions). In this lab we will perform one test of each type.</p>
<div class="try">
<p>
One of the really confusing things about research design is that there are many names for the same type of design.
</p>
<ul>
<li>
Independent and between-subjects design typically mean the same thing - different participants in different conditions
</li>
<li>
Within-subjects, dependent, paired samples, and repeated-measures tend to mean the same participants in all conditions
</li>
<li>
Matched pairs design means different people in different conditions but you have matched participants across the conditions so that they are effectively the same person (e.g. age, IQ, Social Economic Status, etc)
</li>
<li>
Mixed design is when there is a combination of within-subjects and between-subjects designs in the one experiment. For example, say you are looking at attractiveness and dominance of male and female faces. Everyone might see both male and female faces (within) but half of the participants do ratings of attractiveness and half do ratings of trustworthiness (between).
</li>
</ul>
</div>
<p>For the independent t-test we will be using data from Schroeder and Epley (2015). You can take a look at the Psychological Science article here:</p>
<p><a href="https://doi.org/10.1177/0956797615572906">Schroeder, J. and Epley, N. (2015). The sound of intellect: Speech reveals a thoughtful mind, increasing a job candidate’s appeal. Psychological Science, 26, 277–891.</a></p>
<p>The abstract from this article explains more about the different experiments conducted (we will be specifically looking at the dataset from Experiment 4, courtesy of the <a href="https://sites.trinity.edu/osl/data-sets-and-activities/t-test-activities">Open Stats Lab</a>:</p>
<blockquote>
<p>A person’s mental capacities, such as intellect, cannot be observed directly and so are instead inferred from indirect cues. We predicted that a person’s intellect would be conveyed most strongly through a cue closely tied to actual thinking: his or her voice. Hypothetical employers (Experiments 1-3b) and professional recruiters (Experiment 4) watched, listened to, or read job candidates’ pitches about why they should be hired. These evaluators (the employers) rated a candidate as more competent, thoughtful, and intelligent when they heard a pitch rather than read it and, as a result, had a more favourable impression of the candidate and were more interested in hiring the candidate. Adding voice to written pitches, by having trained actors (Experiment 3a) or untrained adults (Experiment 3b) read them, produced the same results. Adding visual cues to audio pitches did not alter evaluations of the candidates. For conveying one’s intellect, it is important that one’s voice, quite literally, be heard.</p>
</blockquote>
<p>To summarise, 39 professional recruiters from Fortune 500 companies evaluated job pitches of M.B.A. candidates from the University of Chicago Booth School of Business. The methods and results appear on pages 887–889 of the article if you want to look at them specifically for more details. The original data, in <strong>wide</strong> format, can be found at the <a href="https://drive.google.com/open?id=0Bz-rhZ21ShvOei1MM24xNndnQ00">Open Stats Lab</a> website for later self-directed learning. Today however, we will be working with a modified version in “tidy” format which can be downloaded from Moodle.</p>
<div id="ttest-a1" class="section level2" number="10.1">
<h2><span class="header-section-number">10.1</span> Activity 1: Set-up</h2>
<p>Your task is to reproduce the results from the article (p. 887).</p>
<ul>
<li>Open R Studio and set the working directory to your chapter folder. Ensure the environment is clear.<br />
</li>
<li>Open a new R Markdown document and save it in your working directory. Call the file “t-tests.”<br />
</li>
<li>Download <a href="evaluators.csv" download>evaluators.csv</a> and <a href="ratings.csv" download>rating.csv</a> and save them in your t-test folder. Make sure that you do not change the file names at all.<br />
</li>
<li>If you’re on the server, avoid a number of issues by restarting the session - click <code>Session</code> - <code>Restart R</code></li>
<li>Delete the default R Markdown welcome text and insert a new code chunk that loads <code>broom</code>, <code>car</code>, <code>effectsize</code>, <code>report</code> and <code>tidyverse</code> using the <code>library()</code> function and loads the data into an object named <code>evaluators</code> using <code>read_csv()</code>. You may need to install some of these packages if you don’t already have them.</li>
</ul>
</div>
<div id="ttest-a2" class="section level2" number="10.2">
<h2><span class="header-section-number">10.2</span> Activity 2: Explore the dataset</h2>
<p>There are a few things we should do to explore the dataset and make working with it a bit easier.</p>
<ul>
<li>Use <code>mutate()</code> and <code>recode()</code> to recode <code>sex</code> into a new variable <code>sex_labels</code> so that <code>1</code> = <code>male</code> and <code>2</code> = <code>female</code>. Be careful - there are multiple functions in different packages called recode, make sure to specify <code>dplyr::recode()</code> to get the right one.</li>
<li>Use <code>mutate()</code> and <code>as.factor()</code> to overwrite <code>sex_labels</code> and <code>condition</code> as factors.<br />
</li>
<li>Use <code>summary()</code> to get an overview of the missing data points in each variable.</li>
</ul>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="t-tests.html#cb158-1" aria-hidden="true" tabindex="-1"></a>evaluators <span class="ot">&lt;-</span> evaluators <span class="sc">%&gt;%</span></span>
<span id="cb158-2"><a href="t-tests.html#cb158-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex_labels =</span> dplyr<span class="sc">::</span><span class="fu">recode</span>(sex, <span class="st">&quot;1&quot;</span> <span class="ot">=</span> <span class="st">&quot;male&quot;</span>, <span class="st">&quot;2&quot;</span> <span class="ot">=</span> <span class="st">&quot;female&quot;</span>),</span>
<span id="cb158-3"><a href="t-tests.html#cb158-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">sex_labels =</span> <span class="fu">as.factor</span>(sex_labels),</span>
<span id="cb158-4"><a href="t-tests.html#cb158-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">condition =</span> <span class="fu">as.factor</span>(condition))</span></code></pre></div>
<ul>
<li>How many participants were noted as being female: <input class='solveme nospaces' size='2' data-answer='["30"]'/></li>
<li>How many participants were noted as being male: <input class='solveme nospaces' size='1' data-answer='["4"]'/></li>
<li>How many data points are missing for <code>sex</code>? <input class='solveme nospaces' size='1' data-answer='["5"]'/></li>
</ul>
</div>
<div id="ttest-a3" class="section level2" number="10.3">
<h2><span class="header-section-number">10.3</span> Activity 3: Ratings</h2>
<p>We are now going calculate an overall intellect rating given by each evaluator - how intellectual the evaluators thought candidates were overall depending on whether or not the evaluators <strong>read</strong> or <strong>listened</strong> to the candidates’ resume pitches. This is calculated by averaging the ratings of <code>competent</code>, <code>thoughtful</code> and <code>intelligent</code> for each evaluator; held within <code>ratings.csv</code>. <strong>Note:</strong> we are not looking at ratings to individual candidates; we are looking at overall ratings for each evaluator. This is a bit confusing but makes sense if you stop to think about it a little.</p>
<p>We will then combine the overall intellect rating with the overall impression ratings and overall hire ratings for each evaluator, with the end goal of having a tibble called <code>ratings2</code> - which has the following structure:</p>
<table>
<thead>
<tr class="header">
<th align="right">eval_id</th>
<th align="left">Category</th>
<th align="right">Rating</th>
<th align="left">condition</th>
<th align="left">sex_labels</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">hire</td>
<td align="right">6.000</td>
<td align="left">listened</td>
<td align="left">female</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="left">impression</td>
<td align="right">7.000</td>
<td align="left">listened</td>
<td align="left">female</td>
</tr>
<tr class="odd">
<td align="right">1</td>
<td align="left">intellect</td>
<td align="right">6.000</td>
<td align="left">listened</td>
<td align="left">female</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">hire</td>
<td align="right">4.000</td>
<td align="left">listened</td>
<td align="left">female</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="left">impression</td>
<td align="right">4.667</td>
<td align="left">listened</td>
<td align="left">female</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">intellect</td>
<td align="right">5.667</td>
<td align="left">listened</td>
<td align="left">female</td>
</tr>
</tbody>
</table>
<p>The following steps describe how to create the above tibble - if you’re feeling comfortable with R, try yourself without using our code. The trick when doing data analysis and data wrangling is to first think about what you want to achieve - the end goal - and then think about what functions you need to use to get there.</p>
<p>Steps 1-3 calculate the new <code>intellect</code> rating. Steps 4 and 5 combine this rating to all other information.</p>
<ol style="list-style-type: decimal">
<li><p>Load the data found in <code>ratings.csv</code> into a tibble called <code>ratings</code>.</p></li>
<li><p><code>filter()</code> only the relevant variables (<strong>thoughtful</strong>, <strong>competent</strong>, <strong>intelligent</strong>) into a new tibble (call it what you like - we use <code>iratings</code>), and calculate a mean <code>Rating</code> for each evaluator.</p></li>
<li><p>Add on a new column called <code>Category</code> where every entry is the word <code>intellect</code>. This tells us that every number in this tibble is an intellect rating.</p></li>
<li><p>Now create a new tibble called <code>ratings2</code> and filter into it just the “impression” and “hire” ratings from the original <code>ratings</code> tibble. Next, bind this tibble with the tibble you created in step 3 to bring together the intellect, impression, and hire ratings, in <code>ratings2</code>.</p></li>
<li><p>Join <code>ratings2</code> with the <code>evaluator</code> tibble that we created in Task 1. Keep only the necessary columns as shown above and arrange by Evaluator and Category.</p></li>
</ol>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="t-tests.html#cb159-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. load in the data</span></span>
<span id="cb159-2"><a href="t-tests.html#cb159-2" aria-hidden="true" tabindex="-1"></a>ratings <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;ratings.csv&quot;</span>)</span>
<span id="cb159-3"><a href="t-tests.html#cb159-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-4"><a href="t-tests.html#cb159-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. first step: pull out the ratings associated with intellect</span></span>
<span id="cb159-5"><a href="t-tests.html#cb159-5" aria-hidden="true" tabindex="-1"></a>iratings <span class="ot">&lt;-</span> ratings <span class="sc">%&gt;%</span></span>
<span id="cb159-6"><a href="t-tests.html#cb159-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Category <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;competent&quot;</span>, <span class="st">&quot;thoughtful&quot;</span>, <span class="st">&quot;intelligent&quot;</span>))</span>
<span id="cb159-7"><a href="t-tests.html#cb159-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-8"><a href="t-tests.html#cb159-8" aria-hidden="true" tabindex="-1"></a><span class="co"># second step: calculate means for each evaluator</span></span>
<span id="cb159-9"><a href="t-tests.html#cb159-9" aria-hidden="true" tabindex="-1"></a>imeans <span class="ot">&lt;-</span> iratings <span class="sc">%&gt;%</span></span>
<span id="cb159-10"><a href="t-tests.html#cb159-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(eval_id) <span class="sc">%&gt;%</span></span>
<span id="cb159-11"><a href="t-tests.html#cb159-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Rating =</span> <span class="fu">mean</span>(Rating))</span>
<span id="cb159-12"><a href="t-tests.html#cb159-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-13"><a href="t-tests.html#cb159-13" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. add Category variable </span></span>
<span id="cb159-14"><a href="t-tests.html#cb159-14" aria-hidden="true" tabindex="-1"></a><span class="co"># this way we can combine with &#39;impression&#39; and &#39;hire&#39; into a single table, very useful!</span></span>
<span id="cb159-15"><a href="t-tests.html#cb159-15" aria-hidden="true" tabindex="-1"></a>imeans2 <span class="ot">&lt;-</span> imeans <span class="sc">%&gt;%</span></span>
<span id="cb159-16"><a href="t-tests.html#cb159-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Category =</span> <span class="st">&quot;intellect&quot;</span>)</span>
<span id="cb159-17"><a href="t-tests.html#cb159-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-18"><a href="t-tests.html#cb159-18" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. &amp; 5. combine into a single table</span></span>
<span id="cb159-19"><a href="t-tests.html#cb159-19" aria-hidden="true" tabindex="-1"></a>ratings2 <span class="ot">&lt;-</span> ratings <span class="sc">%&gt;%</span></span>
<span id="cb159-20"><a href="t-tests.html#cb159-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Category <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;impression&quot;</span>, <span class="st">&quot;hire&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb159-21"><a href="t-tests.html#cb159-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(imeans2) <span class="sc">%&gt;%</span></span>
<span id="cb159-22"><a href="t-tests.html#cb159-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(evaluators, <span class="st">&quot;eval_id&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb159-23"><a href="t-tests.html#cb159-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>age, <span class="sc">-</span>sex) <span class="sc">%&gt;%</span></span>
<span id="cb159-24"><a href="t-tests.html#cb159-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(eval_id, Category)</span></code></pre></div>
</div>
<div id="ttest-a4" class="section level2" number="10.4">
<h2><span class="header-section-number">10.4</span> Activity 4: Visualisation</h2>
<p>You should <strong>always</strong> visualise your data before you run a statistical analysis. Not only will it help you interpret the results of the test but it will give you a better understanding of the spread of your data. For comparing two means, we can take advantage of the many plotting options R provides so we don’t have to settle for a boring (and more importantly, uninformative, bar plot).</p>
<p>To visualise our data we are going to create a violin-boxplot.</p>
<ul>
<li><code>geom_violin()</code> represents density. The fatter the plot, the more data points there are for that . The reason it is called a violin plot is because if your data are normally distributed it should look something like a violin.<br />
</li>
<li><code>geom_boxplot()</code> shows the median and inter-quartile range (see <a href="https://towardsdatascience.com/understanding-boxplots-5e2df7bcbd51">here</a> if you would like more information). The boxplot can also give you a good idea if the data are skewed - the median line should be in the middle of the box, if it’s not, chances are the data are skewed.<br />
</li>
<li>For displaying the mean and confidence intervals, rather than calling a specified geom, we call stat_summary(). <code>fun.data</code> specifies the a summary function that gives us the summary of the data we want to plot, in this case, <code>mean_cl_normal</code> which will calculate the mean plus the upper and lower confidence interval limits. You could also specify <code>mean_se</code> here if you wanted standard error. Finally, <code>geom</code> specifies what shape or plot we want to use to display the summary, in this case we want a <code>pointrange</code> (literally a point (the mean) with a range (the CI)).</li>
</ul>
<p>Run the below code to produce the plot. It is a good idea to save code ‘recipes’ for tasks that you will likely want to repeat in the future. You do not need to memorise lines of code, you only need to understand how to alter examples to work with your specific data set.
* Try setting <code>trim = TRUE</code>, <code>show.legend = FALSE</code> and altering the value of <code>width</code> to see what these arguments do.</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="t-tests.html#cb160-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ratings2, <span class="fu">aes</span>(<span class="at">x =</span> condition, <span class="at">y =</span> Rating)) <span class="sc">+</span></span>
<span id="cb160-2"><a href="t-tests.html#cb160-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">trim =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb160-3"><a href="t-tests.html#cb160-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">fill =</span> condition), <span class="at">width =</span> .<span class="dv">2</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb160-4"><a href="t-tests.html#cb160-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">geom =</span> <span class="st">&quot;pointrange&quot;</span>, <span class="at">fun.data =</span> <span class="st">&quot;mean_cl_normal&quot;</span>)</span></code></pre></div>
<ul>
<li>Look at the plot. In which condition did the evaluators give the higher ratings? <select class='solveme' data-answer='["listened"]'> <option></option> <option>listened</option> <option>read</option></select></li>
</ul>
</div>
<div id="ttest-a5" class="section level2" number="10.5">
<h2><span class="header-section-number">10.5</span> Activity 5: Assumptions</h2>
<p>Before we run the t-test we need to check that the data meet the assumptions for a Welch t-test.</p>
<ol style="list-style-type: decimal">
<li>The data are interval/ratio</li>
<li>The data are independent</li>
<li>The residuals are normally distributed for each group</li>
</ol>
<p>We know that 1 and 2 are true from the design of the experiment, the measures used, and by looking at the data. To test assumption 3, we can create a QQ-plot of the <strong>residuals</strong>. For a between-subject t-test the residuals are the difference between the mean of each group and each data point. E.g., if the mean of group A is 10 and a participant in group A scores 12, the residual for that participant is 2.</p>
<ul>
<li>Run the below code to calculate then plot the residuals. Based upon the plot, do the data meet the assumption of normality? <select class='solveme' data-answer='["Yes"]'> <option></option> <option>Yes</option> <option>No</option></select></li>
</ul>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="t-tests.html#cb161-1" aria-hidden="true" tabindex="-1"></a>ratings2 <span class="ot">&lt;-</span> ratings2 <span class="sc">%&gt;%</span></span>
<span id="cb161-2"><a href="t-tests.html#cb161-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(condition) <span class="sc">%&gt;%</span></span>
<span id="cb161-3"><a href="t-tests.html#cb161-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">group_resid =</span> Rating <span class="sc">-</span> <span class="fu">mean</span>(Rating)) <span class="sc">%&gt;%</span></span>
<span id="cb161-4"><a href="t-tests.html#cb161-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb161-5"><a href="t-tests.html#cb161-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb161-6"><a href="t-tests.html#cb161-6" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(ratings2<span class="sc">$</span>group_resid)</span></code></pre></div>
<p>We can also use a new test that will statistically test the residuals for normality, the <strong>Shapiro-Wilk</strong> test. <code>shapiro.wilk()</code> from Base R assesses if the distribution is significantly different from a normal distribution, so, if the test is significant it means your data is not normal, and if it is non-significant it means it is approximately normal.</p>
<ul>
<li>Run the below code. According to the Shapiro-Wilk test, is the data normally distributed? <select class='solveme' data-answer='["Yes"]'> <option></option> <option>Yes</option> <option>No</option></select></li>
</ul>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="t-tests.html#cb162-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="at">x =</span> ratings2<span class="sc">$</span>group_resid)</span></code></pre></div>
<div class="solution">
<button>
Explain this answer
</button>
<p>The p-value is .2088 which is more than .05, the cut-off for statistical significance.</p>
</div>
<p><br></p>
<ul>
<li>Think back to the lecture. If you ran a Student’s t-test instead of a Welch t-test, what would the 4th assumption be? <select class='solveme' data-answer='["Homogeneity of variance"]'> <option></option> <option>Homogeneity of variance</option> <option>Homoscedascity</option> <option>Nominal data</option></select><br />
</li>
<li>Why should you always use a Welch test instead of a Student t-test? <select class='solveme' data-answer='["Because it performs better if sample sizes and variances are unequal and gives the same result when sample sizes and variances are equal"]'> <option></option> <option>Because it rhymes with squelch which is a funny word</option> <option>Because you are more likely to obtain a signifcant p-value than with Student’s t-test when sample sizes and variances are equal</option> <option>Because it performs better if sample sizes and variances are unequal and gives the same result when sample sizes and variances are equal</option></select>.</li>
</ul>
</div>
<div id="ttest-a6" class="section level2" number="10.6">
<h2><span class="header-section-number">10.6</span> Activity 6: Running the t-test</h2>
<p>We are going to conduct t-tests for the Intellect, Hire and Impression ratings separately; each time comparing evaluators’ overall ratings for the listened group versus overall ratings for the read group to see if there was a significant difference between the two conditions: i.e. did the evaluators who <strong>listened</strong> to pitches give a significant higher or lower rating than evaluators that <strong>read</strong> pitches.</p>
<ul>
<li>First, calculate the mean and SD for each condition and category to help with reporting the descriptive statistics.</li>
</ul>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="t-tests.html#cb163-1" aria-hidden="true" tabindex="-1"></a>group_means <span class="ot">&lt;-</span> ratings2 <span class="sc">%&gt;%</span></span>
<span id="cb163-2"><a href="t-tests.html#cb163-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(condition, Category) <span class="sc">%&gt;%</span></span>
<span id="cb163-3"><a href="t-tests.html#cb163-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">m =</span> <span class="fu">mean</span>(Rating), <span class="at">sd =</span> <span class="fu">sd</span>(Rating))</span></code></pre></div>
<ul>
<li>Next, create separate data sets for the intellect, hire, and impression data using <code>filter()</code>. We have completed intellect for you.</li>
</ul>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="t-tests.html#cb164-1" aria-hidden="true" tabindex="-1"></a>intellect <span class="ot">&lt;-</span> <span class="fu">filter</span>(ratings2, Category <span class="sc">==</span> <span class="st">&quot;intellect&quot;</span>)</span>
<span id="cb164-2"><a href="t-tests.html#cb164-2" aria-hidden="true" tabindex="-1"></a>hire <span class="ot">&lt;-</span> </span>
<span id="cb164-3"><a href="t-tests.html#cb164-3" aria-hidden="true" tabindex="-1"></a>impression <span class="ot">&lt;-</span> </span></code></pre></div>
<p>As you may have realised by now, most of the work of statistics involves the set-up - running the tests is generally very simple. To conduct the t-test we will use <code>t.test()</code> from Base R. This function uses <strong>formula syntax</strong> which you also saw in <code>cor.test()</code>.</p>
<ul>
<li><code>~</code> is called a tilde. It can be read as ‘by.’<br />
</li>
<li>The variable on the left of the tilde is the dependent or outcome variable.</li>
<li>The variable(s) on the right of the tilde is the independent or predictor variable.<br />
</li>
<li>You can read the below code as ‘run a t-test for rating score by condition.’</li>
<li><code>paired = FALSE</code> indicates that we do not want to run a paired-samples test and that our data is from a between-subjects design.</li>
<li>Run the below code and view the output by typing <code>intellect_t</code> in the console.</li>
</ul>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="t-tests.html#cb165-1" aria-hidden="true" tabindex="-1"></a>intellect_t <span class="ot">&lt;-</span> <span class="fu">t.test</span>(Rating <span class="sc">~</span> condition, </span>
<span id="cb165-2"><a href="t-tests.html#cb165-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">paired =</span> <span class="cn">FALSE</span>, </span>
<span id="cb165-3"><a href="t-tests.html#cb165-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> intellect)</span></code></pre></div>
<p>Just like with <code>cor.test()</code>, the output of <code>t.test()</code> is a list type object which can make it harder to work with. This time, we are also going to use the function <code>tidy()</code> from the <code>broom</code> package to convert the output to a tidyverse format.</p>
<ul>
<li>Run the below code. You can read it as “take object intellect_t, and then tidy it.”<br />
</li>
<li>View the object by clicking on <code>results_intellect</code> in the environment.</li>
</ul>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="t-tests.html#cb166-1" aria-hidden="true" tabindex="-1"></a>results_intellect <span class="ot">&lt;-</span> intellect_t <span class="sc">%&gt;%</span></span>
<span id="cb166-2"><a href="t-tests.html#cb166-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>()</span></code></pre></div>
<p>The output is in a nice table format that makes it easy to extract individual values but it is worth explaining what each variable means:</p>
<ul>
<li><p><code>estimate</code> is the difference between the two means</p></li>
<li><p><code>estimate1</code> is the mean of group 1<br />
</p></li>
<li><p><code>estimate2</code> is the mean of group 2<br />
</p></li>
<li><p><code>statistic</code> is the t-statistic<br />
</p></li>
<li><p><code>p.value</code> is the p-value<br />
</p></li>
<li><p><code>parameter</code> is the degrees of freedom<br />
</p></li>
<li><p><code>con.low</code> and <code>conf.high</code> are the confidence interval of the <code>estimate</code></p></li>
<li><p><code>method</code> is the type of test, Welch, Student, paired, or one-sample</p></li>
<li><p><code>alternative</code> is whether the test was one or two-tailed</p></li>
<li><p>Complete the code to run the t-tests for the hire and impression ratings and view the results.</p></li>
</ul>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="t-tests.html#cb167-1" aria-hidden="true" tabindex="-1"></a><span class="co"># t-tests</span></span>
<span id="cb167-2"><a href="t-tests.html#cb167-2" aria-hidden="true" tabindex="-1"></a>hire_t <span class="ot">&lt;-</span> </span>
<span id="cb167-3"><a href="t-tests.html#cb167-3" aria-hidden="true" tabindex="-1"></a>impression_t <span class="ot">&lt;-</span> </span>
<span id="cb167-4"><a href="t-tests.html#cb167-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb167-5"><a href="t-tests.html#cb167-5" aria-hidden="true" tabindex="-1"></a><span class="co"># tidy the output</span></span>
<span id="cb167-6"><a href="t-tests.html#cb167-6" aria-hidden="true" tabindex="-1"></a>results_hire <span class="ot">&lt;-</span></span>
<span id="cb167-7"><a href="t-tests.html#cb167-7" aria-hidden="true" tabindex="-1"></a>results_impression <span class="ot">&lt;-</span></span></code></pre></div>
<div class="warning">
<p>
What do you do if the data don’t meet the assumption of normality? There are a few options.
</p>
<ol style="list-style-type: decimal">
<li>
Transform your data to try and normalise the distribution. We won’t cover this but if you’d like to know more, <a href="https://www.researchgate.net/profile/Jason_Osborne2/publication/200152356_Notes_on_the_Use_of_Data_Transformations/links/0deec5295f1eb10df8000000.pdf">this page</a> is a good start.
</li>
<li>
Use a non-parametric test. The non-parametric equivalent of the independent t-test is the Mann-Whitney and the equivalent of the paired-samples t-test is the Wilcoxon.
</li>
<li>
Do nothing. <a href="https://www.rips-irsp.com/articles/10.5334/irsp.82/">Delacre, Lakens &amp; Leys, 2017</a> argue that with a large enough sample (&gt;30), the Welch test is robust and that using a two-step process actually causes more problems than it solves.
</li>
</ol>
</div>
</div>
<div id="ttest-a7" class="section level2" number="10.7">
<h2><span class="header-section-number">10.7</span> Activity 7: Correcting for multiple comparisons</h2>
<p>Because we’ve run three t-tests we risk inflating our chances of a Type 1 errors due to familywise error. To correct for this we can apply a correction for multiple comparisons.</p>
<p>To do this first of all we need to join all the results of the t-tests
together using <code>bind_rows()</code> which is one of the reasons why it was useful to <code>tidy()</code> the t-test ouput.</p>
<p>First, you specify all of the individual tibbles you want to join and give them a label, and then you specify what the ID column should be named.</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="t-tests.html#cb168-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="at">hire =</span> results_hire, </span>
<span id="cb168-2"><a href="t-tests.html#cb168-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">impression =</span> results_impression, </span>
<span id="cb168-3"><a href="t-tests.html#cb168-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">intellect =</span> results_intellect, </span>
<span id="cb168-4"><a href="t-tests.html#cb168-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">.id =</span> <span class="st">&quot;test&quot;</span>)</span></code></pre></div>
<table>
<colgroup>
<col width="8%" />
<col width="7%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="18%" />
<col width="9%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">test</th>
<th align="center">estimate</th>
<th align="center">estimate1</th>
<th align="center">estimate2</th>
<th align="center">statistic</th>
<th align="center">p.value</th>
<th align="center">parameter</th>
<th align="center">conf.low</th>
<th align="center">conf.high</th>
<th align="center">method</th>
<th align="center">alternative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">hire</td>
<td align="center">1.825397</td>
<td align="center">4.714286</td>
<td align="center">2.888889</td>
<td align="center">2.639949</td>
<td align="center">0.0120842</td>
<td align="center">36.85591</td>
<td align="center">0.4241979</td>
<td align="center">3.226596</td>
<td align="center">Welch Two Sample t-test</td>
<td align="center">two.sided</td>
</tr>
<tr class="even">
<td align="center">impression</td>
<td align="center">1.894333</td>
<td align="center">5.968333</td>
<td align="center">4.074000</td>
<td align="center">2.817175</td>
<td align="center">0.0080329</td>
<td align="center">33.80061</td>
<td align="center">0.5275086</td>
<td align="center">3.261158</td>
<td align="center">Welch Two Sample t-test</td>
<td align="center">two.sided</td>
</tr>
<tr class="odd">
<td align="center">intellect</td>
<td align="center">1.986722</td>
<td align="center">5.635000</td>
<td align="center">3.648278</td>
<td align="center">3.478555</td>
<td align="center">0.0014210</td>
<td align="center">33.43481</td>
<td align="center">0.8253146</td>
<td align="center">3.148130</td>
<td align="center">Welch Two Sample t-test</td>
<td align="center">two.sided</td>
</tr>
</tbody>
</table>
<p>Now, we’re going to add on a column of adjusted p-values using <code>p.adj()</code> and <code>mutate()</code>.</p>
<ul>
<li>Run the below code and then view the adjusted p-values. Are they larger or smaller than the original values? <select class='solveme' data-answer='["Larger"]'> <option></option> <option>Larger</option> <option>Smaller</option></select></li>
</ul>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="t-tests.html#cb169-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> results <span class="sc">%&gt;%</span></span>
<span id="cb169-2"><a href="t-tests.html#cb169-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p.adjusted =</span> <span class="fu">p.adjust</span>(<span class="at">p =</span> p.value, <span class="co"># the column that contains the original p-values</span></span>
<span id="cb169-3"><a href="t-tests.html#cb169-3" aria-hidden="true" tabindex="-1"></a>                               <span class="at">method =</span> <span class="st">&quot;bonferroni&quot;</span>)) <span class="co"># type of correction to apply</span></span></code></pre></div>
</div>
<div id="ttest-a8" class="section level2" number="10.8">
<h2><span class="header-section-number">10.8</span> Activity 8: Effect size</h2>
<p>Before we interpret and write-up the results our last task is to calculate the effect size which for a t-test is Cohen’s D. To do this, we will use the function <code>cohens_d()</code> from the <code>effectsize</code> package. The code is similar to the syntax for <code>t.test()</code>.</p>
<ul>
<li>The first argument should specify the formula, using the same syntax as <code>t.test()</code>, that is <code>dv ~ iv</code>.</li>
<li><code>pooled_sd</code> should be <code>FALSE</code> if you ran a Welch test where the variances are not assumed to be equal and <code>TRUE</code> if you ran a regular Student’s t-test.</li>
<li>Run the below code and then calculate the effect sizes for hire and impression</li>
</ul>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="t-tests.html#cb170-1" aria-hidden="true" tabindex="-1"></a>intellect_d <span class="ot">&lt;-</span> <span class="fu">cohens_d</span>(Rating <span class="sc">~</span> condition, </span>
<span id="cb170-2"><a href="t-tests.html#cb170-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">pooled_sd =</span> <span class="cn">FALSE</span>, </span>
<span id="cb170-3"><a href="t-tests.html#cb170-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> intellect)</span>
<span id="cb170-4"><a href="t-tests.html#cb170-4" aria-hidden="true" tabindex="-1"></a>hire_d <span class="ot">&lt;-</span> </span>
<span id="cb170-5"><a href="t-tests.html#cb170-5" aria-hidden="true" tabindex="-1"></a>impression_d <span class="ot">&lt;-</span> </span></code></pre></div>
</div>
<div id="ttest-a9" class="section level2" number="10.9">
<h2><span class="header-section-number">10.9</span> Activity 9: Interpreting the results</h2>
<ul>
<li><p>Were your results for <code>hire</code> significant? Enter the mean estimates and t-test results (means and t-value to 2 decimal places, p-value to 3 decimal places). Use the adjusted p-values:</p>
<ul>
<li><p>Mean <code>estimate1</code> (listened condition) = <input class='solveme nospaces' size='4' data-answer='["4.71"]'/></p></li>
<li><p>Mean <code>estimate2</code> (read condition) = <input class='solveme nospaces' size='4' data-answer='["2.89"]'/></p></li>
<li><p>t(<input class='solveme nospaces' size='5' data-answer='["36.86"]'/>) = <input class='solveme nospaces' size='4' data-answer='["2.64"]'/>, p = <input class='solveme nospaces' size='5' data-answer='["0.036",".036"]'/></p></li>
</ul></li>
<li><p>Were your results for <code>impression</code> significant? Enter the mean estimates and t-test results (means and t-value to 2 decimal places, p-value to 3 decimal places):</p>
<ul>
<li><p>Mean<code>estimate1</code> (listened condition) = <input class='solveme nospaces' size='4' data-answer='["5.97"]'/></p></li>
<li><p>Mean <code>estimate2</code> (read condition) = <input class='solveme nospaces' size='4' data-answer='["4.07"]'/></p></li>
<li><p>t(<input class='solveme nospaces' size='5' data-answer='["33.80","33.8"]'/>) = <input class='solveme nospaces' size='4' data-answer='["2.82"]'/>, p = <input class='solveme nospaces' size='5' data-answer='["0.024",".024"]'/></p></li>
</ul></li>
<li><p>According to Cohen’s (1988) guidelines, the effect sizes for all three tests are <select class='solveme' data-answer='["Large"]'> <option></option> <option>Small</option> <option>Medium</option> <option>Large</option></select></p></li>
</ul>
</div>
<div id="ttest-a10" class="section level2" number="10.10">
<h2><span class="header-section-number">10.10</span> Activity 10: Write-up</h2>
<p>Copy and paste the below <strong>exactly</strong> into <strong>white space</strong> in your R Markdown document and then knit the file to replicate the results section in the paper (p.887).</p>
<ul>
<li>Note that we haven’t replicated the analysis exactly - the authors of this paper conducted Student’s t-test whilst we have conducted Welch tests and we’ve also applied a multiple comparison correction. Look back at the paper and see what differences this makes.</li>
</ul>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="t-tests.html#cb171-1" aria-hidden="true" tabindex="-1"></a>The pattern of evaluations by professional recruiters replicated the pattern observed <span class="cf">in</span> Experiments <span class="dv">1</span> through 3b (see Fig. <span class="dv">7</span>). Bonferroni<span class="sc">-</span>corrected t<span class="sc">-</span>tests found that <span class="cf">in</span> particular, the recruiters believed that the job candidates had greater intellect<span class="sc">---</span>were more competent, thoughtful, and intelligent<span class="sc">---</span>when they listened to <span class="fu">pitches</span> (<span class="at">M =</span> <span class="st">`</span><span class="at">r results_intellect$estimate1%&gt;% round(2)</span><span class="st">`</span>, <span class="at">SD =</span> <span class="st">`</span><span class="at">r round(group_means$sd[3], 2)</span><span class="st">`</span>) than when they read <span class="fu">pitches</span> (<span class="at">M =</span> <span class="st">`</span><span class="at">r results_intellect$estimate1%&gt;% round(2)</span><span class="st">`</span>, <span class="at">SD =</span> <span class="st">`</span><span class="at">r round(group_means$sd[6], 2)</span><span class="st">`</span>), <span class="fu">t</span>(<span class="st">`</span><span class="at">r round(results_intellect$parameter, 2)</span><span class="st">`</span>) <span class="ot">=</span> <span class="st">`</span><span class="at">r round(results$statistic,2)</span><span class="st">`</span>, p <span class="sc">&lt;</span> <span class="st">`</span><span class="at">r results$p.adjusted[3] %&gt;% round(3)</span><span class="st">`</span>, <span class="dv">95</span>% CI of the difference <span class="ot">=</span> [<span class="st">`</span><span class="at">r round(results_intellect$conf.low, 2)</span><span class="st">`</span>, <span class="st">`</span><span class="at">r round(results_intellect$conf.high, 2)</span><span class="st">`</span>], d <span class="ot">=</span> <span class="st">`</span><span class="at">r round(intellect_d$Cohens_d,2)</span><span class="st">`</span>. </span>
<span id="cb171-2"><a href="t-tests.html#cb171-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb171-3"><a href="t-tests.html#cb171-3" aria-hidden="true" tabindex="-1"></a>The recruiters also formed more positive impressions of the candidates<span class="sc">---</span>rated them as more likeable and had a more positive and less negative impression of them<span class="sc">---</span>when they listened to <span class="fu">pitches</span> (<span class="at">M =</span> <span class="st">`</span><span class="at">r results_impression$estimate1%&gt;% round(2)</span><span class="st">`</span>, <span class="at">SD =</span> <span class="st">`</span><span class="at">r round(group_means$sd[2], 2)</span><span class="st">`</span>) than when they read <span class="fu">pitches</span> (<span class="at">M =</span> <span class="st">`</span><span class="at">r results_impression$estimate2%&gt;% round(2)</span><span class="st">`</span>, <span class="at">SD =</span> <span class="st">`</span><span class="at">r round(group_means$sd[5], 2)</span><span class="st">`</span>, <span class="fu">t</span>(<span class="st">`</span><span class="at">r round(results_impression$parameter,2)</span><span class="st">`</span>) <span class="ot">=</span> <span class="st">`</span><span class="at">r round(results_impression$statistic,2)</span><span class="st">`</span>, p <span class="sc">&lt;</span> <span class="st">`</span><span class="at">r results$p.adjusted[2] %&gt;% round(3)</span><span class="st">`</span>, <span class="dv">95</span>% CI of the <span class="at">difference =</span> [<span class="st">`</span><span class="at">r round(results_impression$conf.low, 2)</span><span class="st">`</span>, <span class="st">`</span><span class="at">r round(results_impression$conf.high, 2)</span><span class="st">`</span>], <span class="at">d =</span> <span class="st">`</span><span class="at">r round(impression_dintellect_d$Cohens_d, 2)</span><span class="st">`</span>. </span>
<span id="cb171-4"><a href="t-tests.html#cb171-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb171-5"><a href="t-tests.html#cb171-5" aria-hidden="true" tabindex="-1"></a>Finally, they also reported being more likely to hire the candidates when they listened to <span class="fu">pitches</span> (<span class="at">M =</span> <span class="st">`</span><span class="at">r results_hire$estimate1 %&gt;% round(2)</span><span class="st">`</span>, <span class="at">SD =</span> <span class="st">`</span><span class="at">r round(group_means$sd[1], 2)</span><span class="st">`</span>) than when they read the same <span class="fu">pitches</span> (<span class="at">M =</span> <span class="st">`</span><span class="at">r results_hire$estimate2 %&gt;% round(2)</span><span class="st">`</span>, <span class="at">SD =</span> <span class="st">`</span><span class="at">r round(group_means$sd[4],2)</span><span class="st">`</span>), <span class="fu">t</span>(<span class="st">`</span><span class="at">r round(results_hire$parameter,2)</span><span class="st">`</span>) <span class="ot">=</span> <span class="st">`</span><span class="at">r round(results_hire$statistic,2)</span><span class="st">`</span>, p <span class="sc">&lt;</span> <span class="st">`</span><span class="at">r results$p.adjusted[1] %&gt;% round(3)</span><span class="st">`</span>, <span class="dv">95</span>% CI of the <span class="at">difference =</span> [<span class="st">`</span><span class="at">r round(results_hire$conf.low, 2)</span><span class="st">`</span>, <span class="st">`</span><span class="at">r round(results_hire$conf.high, 2)</span><span class="st">`</span>], <span class="at">d =</span> <span class="st">`</span><span class="at">r round(hire_dintellect_d$Cohens_d,2)</span><span class="st">`</span>.</span></code></pre></div>
<blockquote>
<p>The pattern of evaluations by professional recruiters replicated the pattern observed in Experiments 1 through 3b (see Fig. 7). Bonferroni-corrected t-tests found that in particular, the recruiters believed that the job candidates had greater intellect—were more competent, thoughtful, and intelligent—when they listened to pitches (M = 5.64, SD = 1.61) than when they read pitches (M = 5.64, SD = 1.91), t(33.43) = 2.64, 2.82, 3.48, p &lt; 0.004, 95% CI of the difference = [0.83, 3.15], d = 1.12, 0.95, 0.43, 1.79.</p>
</blockquote>
<blockquote>
<p>The recruiters also formed more positive impressions of the candidates—rated them as more likeable and had a more positive and less negative impression of them—when they listened to pitches (M = 5.97, SD = 1.92) than when they read pitches (M = 4.07, SD = 2.23, t(33.8) = 2.82, p &lt; 0.024, 95% CI of the difference = [0.53, 3.26], d = 0.91, 0.95, 0.23, 1.56.</p>
</blockquote>
<blockquote>
<p>Finally, they also reported being more likely to hire the candidates when they listened to pitches (M = 4.71, SD = 2.26) than when they read the same pitches (M = 2.89, SD = 2.05), t(36.86) = 2.64, p &lt; 0.036, 95% CI of the difference = [0.42, 3.23], d = 0.84, 0.95, 0.18, 1.5.</p>
</blockquote>
<p>Just like with correlations, you can also used the <code>report()</code> function to produce a report of the individual t-tests. Again, the output it produces is fixed and it must be used with the original list type object, rather than the tidied output. Additionally, <code>report()</code> only takes one t-test at a time, which means that you can’t use the adjusted p-values, but it’s a useful function to know about.</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="t-tests.html#cb172-1" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(intellect_t)</span></code></pre></div>
<pre><code>## Effect sizes were labelled following Cohen&#39;s (1988) recommendations.
## 
## The Welch Two Sample t-test testing the difference of Rating by condition (mean in group listened = 5.63, mean in group read = 3.65) suggests that the effect is negative, statistically significant, and large (difference = -1.99, 95% CI [0.83, 3.15], t(33.43) = 3.48, p &lt; .01; Cohen&#39;s d = 1.20, 95% CI [0.46, 1.93])</code></pre>
</div>
<div id="ttest-a11" class="section level2" number="10.11">
<h2><span class="header-section-number">10.11</span> Activity 11: Paired-samples t-test</h2>
<p>For the final activity we will run a paired-samples t-test for a within-subject design but we will do this much quicker than for the Welch test and just point out the differences in the code.</p>
<p>For this example we will again draw from the <a href="https://sites.trinity.edu/osl/data-sets-and-activities/t-test-activities">Open Stats Lab</a> and look at data from the following paper:</p>
<p><a href="https://journals.sagepub.com/stoken/default+domain/d5HcBHg85XamSXGdYqYN/full">Mehr, S. A., Song. L. A., &amp; Spelke, E. S. (2016). For 5-month-old infants, melodies are social. Psychological Science, 27, 486-501.</a></p>
<p>Parents often sing to their children and, even as infants, children listen to and look at their parents while they are singing. Research by Mehr, Song, and Spelke (2016) sought to explore the psychological function that music has for parents and infants, by examining the hypothesis that particular melodies convey
important social information to infants. Specifically, melodies convey information about social affiliation.</p>
<p>The authors argue that melodies are shared within social groups. Whereas children growing up in one culture may be exposed to certain songs as infants (e.g., “Rock-a-bye Baby”), children growing up in other cultures (or even other groups within a culture) may be exposed to different songs. Thus, when a novel person (someone who the infant has never seen before) sings a familiar song, it may signal to the infant that this new person is a member of their social group.</p>
<p>To test this hypothesis, the researchers recruited 32 infants and their parents to complete an experiment. During their first visit to the lab, the parents were taught a new lullaby (one that neither they nor their infants had heard before). The experimenters asked the parents to sing the new lullaby to their child every day for the next 1-2 weeks. Following this 1-2 week exposure period, the parents and their infant returned to the lab to complete the experimental portion of the study. Infants were first shown a screen with side-by-side videos of two unfamiliar people, each of whom were silently smiling and looking at the infant. The researchers recorded the looking behaviour (or gaze) of the infants during this ‘baseline’ phase. Next, one by one, the two unfamiliar people on the screen sang either the lullaby that the parents learned or a different lullaby (that had the same lyrics and rhythm, but a different melody). Finally, the infants saw the same silent video used at baseline, and the researchers again recorded the looking behaviour of the infants during this ‘test’ phase. For more details on the experiment’s methods, please refer to Mehr et al. (2016) Experiment 1.</p>
<ul>
<li>First, download <a href="Mehr Song and Spelke 2016 Experiment 1.csv" download>Mehr Song and Spelke 2016 Experiment 1.csv</a> and run the below code to load and wrangle the data into the format we need - this code selects only the data we need for the analysis and renames variables to make them easier to work with.</li>
</ul>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="t-tests.html#cb174-1" aria-hidden="true" tabindex="-1"></a>gaze <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;Mehr Song and Spelke 2016 Experiment 1.csv&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb174-2"><a href="t-tests.html#cb174-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(exp1 <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb174-3"><a href="t-tests.html#cb174-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(id, Baseline_Proportion_Gaze_to_Singer,Test_Proportion_Gaze_to_Singer) <span class="sc">%&gt;%</span></span>
<span id="cb174-4"><a href="t-tests.html#cb174-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">baseline =</span> Baseline_Proportion_Gaze_to_Singer,</span>
<span id="cb174-5"><a href="t-tests.html#cb174-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">test =</span> Test_Proportion_Gaze_to_Singer)</span></code></pre></div>
</div>
<div id="ttest-a12" class="section level2" number="10.12">
<h2><span class="header-section-number">10.12</span> Activity 12: Assumptions</h2>
<p>The assumptions for the paired-samples t-test are a little different (although very similar) to the independent t-test.</p>
<ol style="list-style-type: decimal">
<li>The dependent variable must be continuous (interval/ratio).<br />
</li>
<li>All participants should appear in both conditions/groups.</li>
<li>The difference scores should be normally distributed.</li>
</ol>
<p>Aside from the data being paired rather than independent, the key difference is that for the paired-samples test, the assumption of normality if that the differences between each pair of scores are normally distributed, rather than the scores themselves.</p>
<ul>
<li>Run the below code to calculate the difference scores and then conduct the Shapriro-Wilk and QQ-plot as with the independent test.</li>
</ul>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="t-tests.html#cb175-1" aria-hidden="true" tabindex="-1"></a>gaze <span class="ot">&lt;-</span> gaze <span class="sc">%&gt;%</span></span>
<span id="cb175-2"><a href="t-tests.html#cb175-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diff =</span> baseline <span class="sc">-</span> test)</span></code></pre></div>
<p>As you can see, from both the Shapiro-Wilk test and the QQ-plot, the data meet the assumption of normality so we can proceed.</p>
</div>
<div id="ttest-a13" class="section level2" number="10.13">
<h2><span class="header-section-number">10.13</span> Activity 13: Descriptives and visualisations</h2>
<p>It made sense to keep the data in wide-form until this point to make it easy to calculate a column for the difference score, but now we will transform it to tidy data so that we can easily create descriptives and plot the data using <code>tidyverse</code> tools.</p>
<ul>
<li>Run the below code to tidy the data and calculate descriptives and then create the same violin-boxplot as you did for the independent t-test (hint: it is perfectly acceptable to copy and paste the code from Activity 4 and change the data and variable names).</li>
</ul>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="t-tests.html#cb176-1" aria-hidden="true" tabindex="-1"></a>gaze_tidy <span class="ot">&lt;-</span> gaze <span class="sc">%&gt;%</span></span>
<span id="cb176-2"><a href="t-tests.html#cb176-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">names_to =</span> <span class="st">&quot;time&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;looking&quot;</span>, <span class="at">cols =</span> <span class="fu">c</span>(baseline, test)) <span class="sc">%&gt;%</span></span>
<span id="cb176-3"><a href="t-tests.html#cb176-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>diff) <span class="sc">%&gt;%</span></span>
<span id="cb176-4"><a href="t-tests.html#cb176-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(time, id)</span>
<span id="cb176-5"><a href="t-tests.html#cb176-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb176-6"><a href="t-tests.html#cb176-6" aria-hidden="true" tabindex="-1"></a>gaze_descriptives <span class="ot">&lt;-</span> gaze_tidy <span class="sc">%&gt;%</span></span>
<span id="cb176-7"><a href="t-tests.html#cb176-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(time) <span class="sc">%&gt;%</span></span>
<span id="cb176-8"><a href="t-tests.html#cb176-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_looking =</span> <span class="fu">mean</span>(looking, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb176-9"><a href="t-tests.html#cb176-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd_looking =</span> <span class="fu">sd</span>(looking, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
</div>
<div id="ttest-a14" class="section level2" number="10.14">
<h2><span class="header-section-number">10.14</span> Activity 14: Paired-samples t-test</h2>
<p>Finally, we can calculate the t-test and the effect size. The code is almost identical to the independent code with two differences:</p>
<ol style="list-style-type: decimal">
<li>In <code>t.test()</code> you should specify <code>paired = TRUE</code> rather than <code>FALSE</code></li>
<li>In <code>cohens_d()</code> you should specify <code>method = paired</code> rather than <code>pooled_sd</code></li>
</ol>
<ul>
<li>Run the t-test and calculate the effect size. Store the list output version in <code>gaze_t</code> and then use <code>tidy()</code> for <code>gaze_test</code>.</li>
</ul>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="t-tests.html#cb177-1" aria-hidden="true" tabindex="-1"></a>gaze_t <span class="ot">&lt;-</span> </span>
<span id="cb177-2"><a href="t-tests.html#cb177-2" aria-hidden="true" tabindex="-1"></a>gaze_test <span class="ot">&lt;-</span> </span>
<span id="cb177-3"><a href="t-tests.html#cb177-3" aria-hidden="true" tabindex="-1"></a>gaze_d <span class="ot">&lt;-</span> </span></code></pre></div>
<p>The output of the paired-samples t-test is very similar to the independent test, with one exception. Rather than providing the means of both conditions, there is a single <code>estimate</code>. This is the mean <em>difference</em> score between the two conditions.</p>
<ul>
<li><p>Enter the mean estimates and t-test results (means and t-value to 2 decimal places, p-value to 3 decimal places):</p>
<ul>
<li><p>Mean <code>estimate</code> = <input class='solveme nospaces' size='5' data-answer='["-0.07"]'/></p></li>
<li><p>t(<input class='solveme nospaces' size='2' data-answer='["31"]'/>) = <input class='solveme nospaces' size='4' data-answer='["2.42"]'/>, p = <input class='solveme nospaces' size='5' data-answer='["0.022",".022"]'/></p></li>
</ul></li>
</ul>
</div>
<div id="ttest-a15" class="section level2" number="10.15">
<h2><span class="header-section-number">10.15</span> Activity 15: Write-up</h2>
<p>Copy and paste the below <strong>exactly</strong> into <strong>white space</strong> in your R Markdown document and then knit the file to replicate the results section in the paper (p.489).</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="t-tests.html#cb178-1" aria-hidden="true" tabindex="-1"></a>At test, however, the infants selectively attended to the now<span class="sc">-</span>silent singer of the song with the familiar melody; the proportion of time during which they looked toward her was...greater than the proportion at <span class="fu">baseline</span> (difference <span class="cf">in</span> proportion of looking<span class="sc">:</span> <span class="at">M =</span> <span class="st">`</span><span class="at">r gaze_test$estimate %&gt;% round(2)</span><span class="st">`</span>, <span class="at">SD =</span> <span class="st">`</span><span class="at">r sd(gaze$diff, na.rm = TRUE) %&gt;% round(2)</span><span class="st">`</span>, <span class="dv">95</span><span class="sc">% CI = [`r gaze_test$conf.low %</span><span class="er">&gt;</span><span class="sc">% round(2)`, `r gaze_test$conf.high %</span><span class="er">&gt;</span><span class="sc">% round(2)`]), t(`r gaze_test$parameter`) = `r gaze_test$statistic %</span><span class="er">&gt;</span><span class="sc">% round(2)`, p = `r gaze_test$p.value %</span><span class="er">&gt;</span><span class="sc">% round(3)`, d = `r gaze_d$Cohens_d %</span><span class="er">&gt;</span>% <span class="fu">round</span>(<span class="dv">2</span>)<span class="st">`</span><span class="at">.</span></span></code></pre></div>
<blockquote>
<p>At test, however, the infants selectively attended to the now-silent singer of the song with the familiar melody; the proportion of time during which they looked toward her was…greater than the proportion at baseline (difference in proportion of looking: M = -0.07, SD = 0.17, 95% CI = [-0.13, -0.01]), t(31) = -2.42, p = 0.022, d = -0.41.</p>
</blockquote>
<p>Similarly, we can use <code>report()</code> on the original list object to produce an automated write-up.</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="t-tests.html#cb179-1" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(gaze_t)</span></code></pre></div>
<pre><code>## Effect sizes were labelled following Cohen&#39;s (1988) recommendations.
## 
## The Paired t-test testing the difference of looking by time (mean of the differences = -0.07) suggests that the effect is negative, statistically significant, and small (difference = -0.07, 95% CI [-0.13, -0.01], t(31) = -2.42, p &lt; .05; Cohen&#39;s d = -0.43, 95% CI [-0.80, -0.06])</code></pre>
<div id="ttest-fin" class="section level3" number="10.15.1">
<h3><span class="header-section-number">10.15.1</span> Finished!</h3>
<p>That was a long chapter but now that you’ve done all the statistical tests you need to complete your quantitative project - hopefully you will see that it really is true that the hardest part is the set-up and the data wrangling. As we’ve said before, you don’t need to memorise lines of code - you just need to remember where to find examples and to understand which bits of them you need to change. Play around with the examples we have given you and see what changing the values does.</p>
</div>
</div>
<div id="ttest-sols" class="section level2" number="10.16">
<h2><span class="header-section-number">10.16</span> Activity solutions</h2>
<div id="ttest-a1sol" class="section level3" number="10.16.1">
<h3><span class="header-section-number">10.16.1</span> Activity 1</h3>
<div class="solution">
<button>
Activity 1
</button>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="t-tests.html#cb181-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;broom&quot;</span>)</span>
<span id="cb181-2"><a href="t-tests.html#cb181-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;car&quot;</span>)</span>
<span id="cb181-3"><a href="t-tests.html#cb181-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;effectsize&quot;</span>)</span>
<span id="cb181-4"><a href="t-tests.html#cb181-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;report&quot;</span>)</span>
<span id="cb181-5"><a href="t-tests.html#cb181-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;tidyverse&quot;</span>)</span>
<span id="cb181-6"><a href="t-tests.html#cb181-6" aria-hidden="true" tabindex="-1"></a>evaluators <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;evaluators.csv&quot;</span>)</span></code></pre></div>
</div>
<p><strong>click the tab to see the solution</strong>
<br></p>
</div>
<div id="ttest-a2sol" class="section level3" number="10.16.2">
<h3><span class="header-section-number">10.16.2</span> Activity 2</h3>
<div class="solution">
<button>
Activity 2
</button>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="t-tests.html#cb182-1" aria-hidden="true" tabindex="-1"></a>evaluators <span class="ot">&lt;-</span> evaluators <span class="sc">%&gt;%</span></span>
<span id="cb182-2"><a href="t-tests.html#cb182-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex_labels =</span> dplyr<span class="sc">::</span><span class="fu">recode</span>(sex, <span class="st">&quot;1&quot;</span> <span class="ot">=</span> <span class="st">&quot;male&quot;</span>, <span class="st">&quot;2&quot;</span> <span class="ot">=</span> <span class="st">&quot;female&quot;</span>),</span>
<span id="cb182-3"><a href="t-tests.html#cb182-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">sex_labels =</span> <span class="fu">as.factor</span>(sex_labels),</span>
<span id="cb182-4"><a href="t-tests.html#cb182-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">condition =</span> <span class="fu">as.factor</span>(condition))</span>
<span id="cb182-5"><a href="t-tests.html#cb182-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(evaluators)</span></code></pre></div>
</div>
<p><strong>click the tab to see the solution</strong>
<br></p>
</div>
<div id="ttest-a6sol" class="section level3" number="10.16.3">
<h3><span class="header-section-number">10.16.3</span> Activity 6</h3>
<div class="solution">
<button>
Activity 6
</button>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="t-tests.html#cb183-1" aria-hidden="true" tabindex="-1"></a>intellect <span class="ot">&lt;-</span> <span class="fu">filter</span>(ratings2, Category <span class="sc">==</span> <span class="st">&quot;intellect&quot;</span>)</span>
<span id="cb183-2"><a href="t-tests.html#cb183-2" aria-hidden="true" tabindex="-1"></a>hire <span class="ot">&lt;-</span> <span class="fu">filter</span>(ratings2, Category <span class="sc">==</span> <span class="st">&quot;hire&quot;</span>)</span>
<span id="cb183-3"><a href="t-tests.html#cb183-3" aria-hidden="true" tabindex="-1"></a>impression <span class="ot">&lt;-</span> <span class="fu">filter</span>(ratings2, Category <span class="sc">==</span> <span class="st">&quot;impression&quot;</span>)</span></code></pre></div>
</div>
<p><strong>click the tab to see the solution</strong>
<br></p>
</div>
<div id="ttest-a8sol" class="section level3" number="10.16.4">
<h3><span class="header-section-number">10.16.4</span> Activity 8</h3>
<div class="solution">
<button>
Activity 7
</button>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="t-tests.html#cb184-1" aria-hidden="true" tabindex="-1"></a>intellect_d <span class="ot">&lt;-</span> <span class="fu">cohens_d</span>(Rating <span class="sc">~</span> condition, </span>
<span id="cb184-2"><a href="t-tests.html#cb184-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">pooled_sd =</span> <span class="cn">FALSE</span>, </span>
<span id="cb184-3"><a href="t-tests.html#cb184-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> intellect)</span>
<span id="cb184-4"><a href="t-tests.html#cb184-4" aria-hidden="true" tabindex="-1"></a>hire_d <span class="ot">&lt;-</span> <span class="fu">cohens_d</span>(Rating <span class="sc">~</span> condition, </span>
<span id="cb184-5"><a href="t-tests.html#cb184-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">pooled_sd =</span> <span class="cn">FALSE</span>, </span>
<span id="cb184-6"><a href="t-tests.html#cb184-6" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> hire)</span>
<span id="cb184-7"><a href="t-tests.html#cb184-7" aria-hidden="true" tabindex="-1"></a>impression_d <span class="ot">&lt;-</span> <span class="fu">cohens_d</span>(Rating <span class="sc">~</span> condition, </span>
<span id="cb184-8"><a href="t-tests.html#cb184-8" aria-hidden="true" tabindex="-1"></a>                      <span class="at">pooled_sd =</span> <span class="cn">FALSE</span>, </span>
<span id="cb184-9"><a href="t-tests.html#cb184-9" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> impression)</span></code></pre></div>
</div>
</div>
<div id="ttest-a12sol" class="section level3" number="10.16.5">
<h3><span class="header-section-number">10.16.5</span> Activity 12</h3>
<div class="solution">
<button>
Activity 12
</button>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="t-tests.html#cb185-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="at">x =</span> gaze<span class="sc">$</span>diff)</span>
<span id="cb185-2"><a href="t-tests.html#cb185-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb185-3"><a href="t-tests.html#cb185-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(gaze<span class="sc">$</span>diff)</span></code></pre></div>
</div>
<p><strong>click the tab to see the solution</strong>
<br></p>
</div>
<div id="ttest-a13sol" class="section level3" number="10.16.6">
<h3><span class="header-section-number">10.16.6</span> Activity 13</h3>
<div class="solution">
<button>
Activity 13
</button>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="t-tests.html#cb186-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create summary data to use with `geom_pointrange()`</span></span>
<span id="cb186-2"><a href="t-tests.html#cb186-2" aria-hidden="true" tabindex="-1"></a>summary_gaze<span class="ot">&lt;-</span>gaze_tidy<span class="sc">%&gt;%</span></span>
<span id="cb186-3"><a href="t-tests.html#cb186-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(time)<span class="sc">%&gt;%</span></span>
<span id="cb186-4"><a href="t-tests.html#cb186-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(looking),</span>
<span id="cb186-5"><a href="t-tests.html#cb186-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">min =</span> <span class="fu">mean</span>(looking) <span class="sc">-</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)<span class="sc">*</span><span class="fu">sd</span>(looking)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">n</span>()), <span class="co">#confidence intervals</span></span>
<span id="cb186-6"><a href="t-tests.html#cb186-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">max =</span> <span class="fu">mean</span>(looking) <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)<span class="sc">*</span><span class="fu">sd</span>(looking)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">n</span>()))</span>
<span id="cb186-7"><a href="t-tests.html#cb186-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb186-8"><a href="t-tests.html#cb186-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb186-9"><a href="t-tests.html#cb186-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gaze_tidy, <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> looking)) <span class="sc">+</span></span>
<span id="cb186-10"><a href="t-tests.html#cb186-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">trim =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb186-11"><a href="t-tests.html#cb186-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">fill =</span> time), <span class="at">width =</span> .<span class="dv">2</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb186-12"><a href="t-tests.html#cb186-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="at">data =</span> summary_gaze,</span>
<span id="cb186-13"><a href="t-tests.html#cb186-13" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> mean, <span class="at">ymin=</span>min, <span class="at">ymax=</span>max),</span>
<span id="cb186-14"><a href="t-tests.html#cb186-14" aria-hidden="true" tabindex="-1"></a>                  <span class="at">shape =</span> <span class="dv">20</span>, </span>
<span id="cb186-15"><a href="t-tests.html#cb186-15" aria-hidden="true" tabindex="-1"></a>                  <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.1</span>), <span class="at">show.legend =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
</div>
<p><strong>click the tab to see the solution</strong>
<br></p>
</div>
<div id="ttest-a14sol" class="section level3" number="10.16.7">
<h3><span class="header-section-number">10.16.7</span> Activity 14</h3>
<div class="solution">
<button>
Activity 14
</button>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="t-tests.html#cb187-1" aria-hidden="true" tabindex="-1"></a>gaze_t <span class="ot">&lt;-</span> <span class="fu">t.test</span>(looking <span class="sc">~</span> time, <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">data =</span> gaze_tidy)</span>
<span id="cb187-2"><a href="t-tests.html#cb187-2" aria-hidden="true" tabindex="-1"></a>gaze_test <span class="ot">&lt;-</span>  gaze_t <span class="sc">%&gt;%</span> <span class="fu">tidy</span>()</span>
<span id="cb187-3"><a href="t-tests.html#cb187-3" aria-hidden="true" tabindex="-1"></a>gaze_d <span class="ot">&lt;-</span> <span class="fu">cohens_d</span>(looking <span class="sc">~</span> time, <span class="at">method =</span> <span class="st">&quot;paired&quot;</span>, <span class="at">data =</span> gaze_tidy)</span></code></pre></div>
</div>
<p><strong>click the tab to see the solution</strong>
<br></p>

</div>
</div>
</div>
<div class="psyteachr_footer">
  
</div>
<script>

/* update total correct if #total_correct exists */
update_total_correct = function() {
  if (t = document.getElementById("total_correct")) {
    t.innerHTML =
      document.getElementsByClassName("correct").length + " of " +
      document.getElementsByClassName("solveme").length + " correct";
  }
}

/* solution button toggling function */
b_func = function() {
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "");
  }
  
  if (my_answer !== "" & real_answers.includes(my_answer)) {
    cl.add("correct");
  } else {
    cl.remove("correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol){
    var tol = JSON.parse(this.dataset.tol);  
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("correct");
    } else {
      cl.remove("correct");
    }  
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("correct");
    }  
  }
  
  update_total_correct();
}

window.onload = function() {
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('solution')) {
      buttons[i].onclick = b_func;
    }
  }
  
  /* set up solveme inputs */
  var solveme = document.getElementsByClassName("solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off"); 
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";
    
    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;
    
    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="correlation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="power-and-error.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"],
"google": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": {},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
